# Experiment: 10D cond 1D

dim(x)=9, dim(y)=1 — comparing LGD vs LGD-CM.

In [1]:
# ============================================================
# CONFIG — only this cell changes between notebooks
# ============================================================
EXPERIMENT_NAME   = "10D_cond_1D"
GLOBAL_SEED       = 42
FORCE_RETRAIN     = False

BASE_DIR          = "/content/conditional-matching-paper/simulations"
PARAMS_DIR        = f"{BASE_DIR}/params"
CHECKPOINT_DIR    = f"{BASE_DIR}/checkpoints/{EXPERIMENT_NAME}"
RESULTS_DIR       = f"{BASE_DIR}/results/{EXPERIMENT_NAME}"

# Architecture — Diffusion models
NBLOCKS           = 8
NUNITS            = 512

# Architecture — Consistency Model
NBLOCKS_CM        = 8
NUNITS_CM         = 512

# Training — Diffusion
NEPOCHS           = 20_000
BATCH_SIZE        = 512

# Training — Consistency Model
NEPOCHS_CM        = 40_000
BATCH_SIZE_CM     = 4_096

# Diffusion
DIFFUSION_STEPS   = 100

# Optimization
N_ATTEMP_OPTIM              = 25
NSAMPLES_IN_OPTIM_FOR_MMD   = 250
NUM_X_T_LGD                 = 3
NUM_X_T_LGD_CM              = 10

# GMM dimensions
CONDITION_ON      = 9   # dim(x)=9, dim(y)=1

In [2]:
!pip install flow_matching -q
!pip install POT -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.7/48.7 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 72.5 MB/s eta 0:00:00

In [3]:
import os, sys
from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF')
if hf_token:
    login(token=hf_token)
else:
    login()

if 'google.colab' in str(get_ipython()):
    import getpass
    !pip install -q diffusers transformers accelerate xformers
    !pip install -q scikit-learn matplotlib Pillow

    github_token = userdata.get('GITHUB')
    token = github_token if github_token else getpass.getpass("Enter your GitHub personal access token: ")

    repo_url  = f"https://{token}@github.com/orineo1/conditional-matching-paper.git"
    repo_name = "conditional-matching-paper"
    branch    = "adding-simu-compare"

    if not os.path.exists(repo_name):
        !git clone {repo_url}
    else:
        print(f"Repo '{repo_name}' already cloned — pulling latest...")
        !cd {repo_name} && git pull

    !cd {repo_name} && git checkout {branch}

# ── point Python at simulations/src where all .py modules live ──
src_path = f"/content/{repo_name}/simulations/src"
if src_path not in sys.path:
    sys.path.insert(0, src_path)

print(f"Branch: {branch}")
print(f"src path on sys.path: {src_path}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 90.1 MB/s eta 0:00:00
Cloning into 'conditional-matching-paper'...
remote: Enumerating objects: 5494, done.
remote: Counting objects: 100% (452/452), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 5494 (delta 387), reused 346 (delta 308), pack-reused 5042 (from 1)
Receiving objects: 100% (5494/5494), 1.07 GiB | 16.55 MiB/s, done.
Resolving deltas: 100% (1432/1432), done.
Branch 'adding-simu-compare' set up to track remote branch 'adding-simu-compare' from 'origin'.
Switched to a new branch 'adding-simu-compare'
Branch: adding-simu-compare
src path on sys.path: /content/conditional-matching-paper/simulations/src

In [4]:
import os, sys, time, json
import importlib
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
from functools import partial
from tqdm import trange

import Diffusion
import LossFunctions
import ConsistencyModels
import dist_utils
import Optimization
import experiment_utils
from ConsistencyModels import ConsistencyModeliCT
import evalModels

for mod in [Diffusion, LossFunctions, ConsistencyModels,
            dist_utils, Optimization, experiment_utils]:
    importlib.reload(mod)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(PARAMS_DIR,     exist_ok=True)
print("Imports done.")

Imports done.

In [5]:
env_info = experiment_utils.get_environment_info()
experiment_utils.print_environment_info(env_info)

============================================================
ENVIRONMENT INFO
============================================================
  timestamp: 2026-04-10T16:49:35.716339
  torch_version: 2.10.0+cu128
  cuda_available: True
  cuda_version: 12.8
  device_name: NVIDIA L4
  packages:
    torch: 2.10.0+cu128
    numpy: 2.0.2
    flow_matching: 1.0.10
    POT: 0.9.6.post1
    matplotlib: 3.10.0
    pandas: 2.2.2
    tqdm: 4.67.3
============================================================

In [6]:
experiment_utils.set_global_seed(GLOBAL_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

[Seed] All random seeds set to 42
Using device: cuda

## GMM Parameters

In [7]:
# ============================================================
# GMM PARAMETERS
# Priority:
#   1. Load from PARAMS_DIR  (shared across runs, committed to repo)
#   2. Load from RESULTS_DIR (fallback from a previous run)
#   3. Generate fresh and save to both dirs
#
# To force regeneration: set FORCE_REGENERATE_PARAMS = True
# ============================================================
FORCE_REGENERATE_PARAMS = False

def _load_params():
    """Try PARAMS_DIR first, then RESULTS_DIR."""
    loaded = experiment_utils.load_gmm_params(PARAMS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from PARAMS_DIR: {PARAMS_DIR}")
        return loaded
    loaded = experiment_utils.load_gmm_params(RESULTS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from RESULTS_DIR: {RESULTS_DIR}")
        return loaded
    return None

loaded = None if FORCE_REGENERATE_PARAMS else _load_params()

if loaded is not None:
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = loaded
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()
else:
    print("[GMM] Generating fresh parameters...")
    experiment_utils.set_global_seed(GLOBAL_SEED)   # seed generation for reproducibility
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = \
        dist_utils.get_param_mog_with_target(
            dim_data=10, num_components=4, device='cpu',
            conditional_modes=2, distanceOrScale="Distance"
        )
    mog_means, mog_variances, weights = dist_utils.filter_and_normalize(
        mog_means, mog_variances, weights, threshold=0.001
    )
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()

    # save to PARAMS_DIR (canonical, share across runs)
    experiment_utils.save_gmm_params(
        mu_list, Sigma_list, alpha,
        mog_means, mog_variances, weights, x_star,
        PARAMS_DIR, EXPERIMENT_NAME
    )


print(f"x_star = {x_star}")
print(f"Number of conditional modes after filtering: {len(mog_means)}")

[GMM] Generating fresh parameters...
[Seed] All random seeds set to 42
[GMM] Parameters saved to /content/conditional-matching-paper/simulations/params/10D_cond_1D_gmm_params.pt
x_star = tensor([ -4.5404,   2.7114,   0.5513, -11.2950,   3.0335,  -0.6915,   4.1551,
         -1.2385,  -4.0147])
Number of conditional modes after filtering: 2

/content/conditional-matching-paper/simulations/src/dist_utils.py:466: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  exponent = -0.5 * diff.T @ Sigma_22_inv @ diff

## Data

In [9]:
experiment_utils.set_global_seed(GLOBAL_SEED)
X = dist_utils.generate_mog_samples(25_000, mu_list, Sigma_list, alpha).float().to(device)

[Seed] All random seeds set to 42

## Train Models

### Consistency Model — P(Y|X=x)

In [10]:
experiment_utils.set_global_seed(GLOBAL_SEED)

B, C      = X.shape
nfeatures = C - CONDITION_ON
data_generator_cm = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha
)

Cos_ConsistencyModeliCT = ConsistencyModeliCT(
    nfeatures=nfeatures, condition_on=CONDITION_ON,
    nunits=NUNITS_CM, depth=NBLOCKS_CM
)

_loaded_cm = experiment_utils.load_model_checkpoint(
    Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_cm:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    Cos_ConsistencyModeliCT.train_model(
        X=None, nepochs=NEPOCHS_CM, batch_size=BATCH_SIZE_CM,
        device=device, condition=CONDITION_ON,
        data_generator=data_generator_cm, use_improved_training=True
    )
    experiment_utils.save_model_checkpoint(
        Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] No checkpoint found for CM at /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_CM_seed42.pt
[Seed] All random seeds set to 42

loss: 0.328974, mu: 0.0000, N: 1281: 100%|██████████| 40000/40000 [08:18<00:00, 80.20it/s]

[Checkpoint] CM saved to /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_CM_seed42.pt

### Diffusion — P(Y|X=x)

In [11]:
experiment_utils.set_global_seed(GLOBAL_SEED)

X_train   = dist_utils.generate_mog_samples(1_000, mu_list, Sigma_list, alpha).float().to(device)
nfeatures = X_train.shape[1]

data_generator_diff_cond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha, kernel_func=None
)

model_cond = Diffusion.DiffusionModel(
    nfeatures=nfeatures, nblocks=NBLOCKS, nunits=NUNITS,
    condition=True, condition_on=CONDITION_ON,
    diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_cond = experiment_utils.load_model_checkpoint(
    model_cond, "Diffusion_cond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_cond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_cond.train_model(
        None, data_generator=data_generator_diff_cond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_cond, "Diffusion_cond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] No checkpoint found for Diffusion_cond at /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt
[Seed] All random seeds set to 42

loss: 0.162894: 100%|██████████| 20000/20000 [29:20<00:00, 11.36it/s]

[Checkpoint] Diffusion_cond saved to /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt

### Diffusion — P(X=x)

In [12]:
experiment_utils.set_global_seed(GLOBAL_SEED)

data_generator_diff_uncond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha,
    kernel_func=lambda X: X[:, :CONDITION_ON]
)

model_uncond = Diffusion.DiffusionModel(
    nfeatures=CONDITION_ON, nblocks=NBLOCKS, nunits=NUNITS,
    condition=False, diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_uncond = experiment_utils.load_model_checkpoint(
    model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_uncond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_uncond.train_model(
        None, data_generator=data_generator_diff_uncond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] No checkpoint found for Diffusion_uncond at /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt
[Seed] All random seeds set to 42

loss: 0.663864: 100%|██████████| 20000/20000 [22:36<00:00, 14.74it/s]

[Checkpoint] Diffusion_uncond saved to /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt

## Optimize

### LGD

In [13]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_list = []
l2_gmm_LGD_list   = []
l2_x_LGD_list     = []
lgd_times         = []
final_loss_LGD    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, model_cond, mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        num_x_t=NUM_X_T_LGD
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_times.append(end_time - start_time)
    final_loss_LGD.append(final_loss)
    best_x_t_LGD_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_list.append(l2_gmm)
    l2_x_LGD_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [04:01<1:36:40, 241.68s/it]

[1] seed=42 | L2 GMM: 0.118900 | L2 to x*: 38.156750

  8%|▊         | 2/25 [08:03<1:32:43, 241.89s/it]

[2] seed=43 | L2 GMM: 0.162272 | L2 to x*: 4.511035

 12%|█▏        | 3/25 [12:05<1:28:39, 241.79s/it]

[3] seed=44 | L2 GMM: 0.117133 | L2 to x*: 35.343548

 16%|█▌        | 4/25 [16:06<1:24:35, 241.69s/it]

[4] seed=45 | L2 GMM: 0.120033 | L2 to x*: 36.023560

 20%|██        | 5/25 [20:08<1:20:29, 241.47s/it]

[5] seed=46 | L2 GMM: 0.502105 | L2 to x*: 6.677496

 24%|██▍       | 6/25 [24:10<1:16:32, 241.71s/it]

[6] seed=47 | L2 GMM: 0.086448 | L2 to x*: 4.174766

 28%|██▊       | 7/25 [28:12<1:12:34, 241.91s/it]

[7] seed=48 | L2 GMM: 0.063537 | L2 to x*: 3.270805

 32%|███▏      | 8/25 [32:13<1:08:28, 241.66s/it]

[8] seed=49 | L2 GMM: 0.123683 | L2 to x*: 39.571663

 36%|███▌      | 9/25 [36:16<1:04:32, 242.00s/it]

[9] seed=50 | L2 GMM: 0.077875 | L2 to x*: 3.831578

 40%|████      | 10/25 [40:17<1:00:27, 241.87s/it]

[10] seed=51 | L2 GMM: 0.128300 | L2 to x*: 33.733101

 44%|████▍     | 11/25 [44:19<56:23, 241.65s/it]

[11] seed=52 | L2 GMM: 0.346478 | L2 to x*: 2.666171

 48%|████▊     | 12/25 [48:20<52:19, 241.51s/it]

[12] seed=53 | L2 GMM: 0.315288 | L2 to x*: 3.450382

 52%|█████▏    | 13/25 [52:22<48:19, 241.63s/it]

[13] seed=54 | L2 GMM: 0.119891 | L2 to x*: 38.778332

 56%|█████▌    | 14/25 [56:23<44:16, 241.53s/it]

[14] seed=55 | L2 GMM: 0.305054 | L2 to x*: 3.004593

 60%|██████    | 15/25 [1:00:24<40:13, 241.38s/it]

[15] seed=56 | L2 GMM: 0.118689 | L2 to x*: 39.354290

 64%|██████▍   | 16/25 [1:04:27<36:15, 241.72s/it]

[16] seed=57 | L2 GMM: 0.119040 | L2 to x*: 4.138253

 68%|██████▊   | 17/25 [1:08:29<32:16, 242.06s/it]

[17] seed=58 | L2 GMM: 0.850743 | L2 to x*: 20.495142

 72%|███████▏  | 18/25 [1:12:31<28:14, 242.02s/it]

[18] seed=59 | L2 GMM: 0.125772 | L2 to x*: 37.626099

 76%|███████▌  | 19/25 [1:16:33<24:12, 242.02s/it]

[19] seed=60 | L2 GMM: 0.696535 | L2 to x*: 14.702456

 80%|████████  | 20/25 [1:20:35<20:09, 241.93s/it]

[20] seed=61 | L2 GMM: 0.053336 | L2 to x*: 2.813294

 84%|████████▍ | 21/25 [1:24:35<16:05, 241.35s/it]

[21] seed=62 | L2 GMM: 0.284983 | L2 to x*: 2.807638

 88%|████████▊ | 22/25 [1:28:36<12:03, 241.24s/it]

[22] seed=63 | L2 GMM: 0.220675 | L2 to x*: 3.298697

 92%|█████████▏| 23/25 [1:32:37<08:02, 241.25s/it]

[23] seed=64 | L2 GMM: 0.102029 | L2 to x*: 3.002735

 96%|█████████▌| 24/25 [1:36:39<04:01, 241.37s/it]

[24] seed=65 | L2 GMM: 0.238032 | L2 to x*: 3.141267

100%|██████████| 25/25 [1:40:41<00:00, 241.66s/it]

[25] seed=66 | L2 GMM: 0.126743 | L2 to x*: 38.400215

### LGD-CM

In [14]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_CM_list = []
l2_gmm_LGD_CM_list   = []
l2_x_LGD_CM_list     = []
lgd_cm_times         = []
final_loss_LGD_CM    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, Cos_ConsistencyModeliCT,
        mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        CM=True, FLAG=False, num_x_t=NUM_X_T_LGD_CM
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_cm_times.append(end_time - start_time)
    final_loss_LGD_CM.append(final_loss)
    best_x_t_LGD_CM_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_CM_list.append(l2_gmm)
    l2_x_LGD_CM_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [00:52<21:01, 52.54s/it]

[1] seed=42 | L2 GMM: 0.161426 | L2 to x*: 2.093758

  8%|▊         | 2/25 [01:45<20:07, 52.51s/it]

[2] seed=43 | L2 GMM: 0.504416 | L2 to x*: 6.303494

 12%|█▏        | 3/25 [02:37<19:10, 52.30s/it]

[3] seed=44 | L2 GMM: 0.787433 | L2 to x*: 16.506624

 16%|█▌        | 4/25 [03:29<18:19, 52.37s/it]

[4] seed=45 | L2 GMM: 0.360602 | L2 to x*: 2.283705

 20%|██        | 5/25 [04:22<17:29, 52.49s/it]

[5] seed=46 | L2 GMM: 0.295724 | L2 to x*: 3.015928

 24%|██▍       | 6/25 [05:14<16:36, 52.47s/it]

[6] seed=47 | L2 GMM: 0.191075 | L2 to x*: 2.128852

 28%|██▊       | 7/25 [06:06<15:40, 52.23s/it]

[7] seed=48 | L2 GMM: 0.013928 | L2 to x*: 2.514520

 32%|███▏      | 8/25 [06:57<14:43, 51.95s/it]

[8] seed=49 | L2 GMM: 0.040398 | L2 to x*: 2.340855

 36%|███▌      | 9/25 [07:49<13:49, 51.85s/it]

[9] seed=50 | L2 GMM: 0.504536 | L2 to x*: 14.664448

 40%|████      | 10/25 [08:41<12:57, 51.82s/it]

[10] seed=51 | L2 GMM: 0.155981 | L2 to x*: 4.635317

 44%|████▍     | 11/25 [09:32<12:03, 51.65s/it]

[11] seed=52 | L2 GMM: 0.089647 | L2 to x*: 2.261083

 48%|████▊     | 12/25 [10:23<11:08, 51.40s/it]

[12] seed=53 | L2 GMM: 0.504231 | L2 to x*: 10.260704

 52%|█████▏    | 13/25 [11:15<10:18, 51.51s/it]

[13] seed=54 | L2 GMM: 0.497304 | L2 to x*: 7.531044

 56%|█████▌    | 14/25 [12:06<09:27, 51.58s/it]

[14] seed=55 | L2 GMM: 0.149083 | L2 to x*: 31.412683

 60%|██████    | 15/25 [12:58<08:35, 51.52s/it]

[15] seed=56 | L2 GMM: 0.477308 | L2 to x*: 3.639278

 64%|██████▍   | 16/25 [13:49<07:43, 51.53s/it]

[16] seed=57 | L2 GMM: 0.303522 | L2 to x*: 1.739390

 68%|██████▊   | 17/25 [14:41<06:51, 51.49s/it]

[17] seed=58 | L2 GMM: 0.222189 | L2 to x*: 2.224475

 72%|███████▏  | 18/25 [15:32<06:00, 51.53s/it]

[18] seed=59 | L2 GMM: 0.036308 | L2 to x*: 2.178733

 76%|███████▌  | 19/25 [16:23<05:07, 51.33s/it]

[19] seed=60 | L2 GMM: 0.139964 | L2 to x*: 1.655398

 80%|████████  | 20/25 [17:14<04:16, 51.35s/it]

[20] seed=61 | L2 GMM: 0.052780 | L2 to x*: 2.292236

 84%|████████▍ | 21/25 [18:06<03:25, 51.42s/it]

[21] seed=62 | L2 GMM: 0.168864 | L2 to x*: 3.410380

 88%|████████▊ | 22/25 [18:58<02:34, 51.47s/it]

[22] seed=63 | L2 GMM: 0.307284 | L2 to x*: 3.431517

 92%|█████████▏| 23/25 [19:49<01:42, 51.45s/it]

[23] seed=64 | L2 GMM: 0.190525 | L2 to x*: 1.726624

 96%|█████████▌| 24/25 [20:40<00:51, 51.39s/it]

[24] seed=65 | L2 GMM: 0.307000 | L2 to x*: 2.255395

100%|██████████| 25/25 [21:32<00:00, 51.70s/it]

[25] seed=66 | L2 GMM: 0.147855 | L2 to x*: 35.580593

## Results

In [15]:
rows = [
    experiment_utils.summary_row("LGD",    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.summary_row("LGD-CM", l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df = pd.DataFrame(rows).set_index("Method")
display(df)

rows_top10 = [
    experiment_utils.top10_stats("LGD",    final_loss_LGD,    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.top10_stats("LGD-CM", final_loss_LGD_CM, l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df_top10 = pd.DataFrame(rows_top10).set_index("Method")
display(df_top10)

,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s)
Method,,,,,,
LGD,0.2209,0.1945,16.9190,15.9096,241.64,0.62
LGD-CM,0.2644,0.1885,6.7235,8.8066,51.69,0.49

,Loss mean,Loss std,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s),Top-k selected
Method,,,,,,,,,
LGD,0.0887,0.0824,0.2238,0.2439,5.6214,5.0669,241.96,0.65,10
LGD-CM,0.0947,0.0386,0.1254,0.0708,2.2535,0.4579,51.61,0.49,10

In [16]:
def to_python(val):
    if isinstance(val, torch.Tensor):
        return val.detach().cpu().tolist()
    if isinstance(val, np.ndarray):
        return val.tolist()
    if hasattr(val, "item"):
        return val.item()
    return val

results = {
    "experiment":  EXPERIMENT_NAME,
    "seed":        GLOBAL_SEED,
    "environment": env_info,
    "LGD": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_list],
        "final_loss": [to_python(l) for l in final_loss_LGD],
        "l2_gmm":     l2_gmm_LGD_list,
        "l2_x":       l2_x_LGD_list,
        "times":      lgd_times,
    },
    "LGD-CM": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_CM_list],
        "final_loss": [to_python(l) for l in final_loss_LGD_CM],
        "l2_gmm":     l2_gmm_LGD_CM_list,
        "l2_x":       l2_x_LGD_CM_list,
        "times":      lgd_cm_times,
    },
    "meta": {
        "n_attemp_optim":            N_ATTEMP_OPTIM,
        "nsamples_in_optim_for_mmd": NSAMPLES_IN_OPTIM_FOR_MMD,
        "x_star":                    to_python(x_star),
    },
}

path = os.path.join(RESULTS_DIR, f"{EXPERIMENT_NAME}_results_seed{GLOBAL_SEED}.json")
with open(path, "w") as f:
    json.dump(results, f, indent=2)
print(f"Results saved to {path}")

Results saved to /content/conditional-matching-paper/simulations/results/10D_cond_1D/10D_cond_1D_results_seed42.json