# Experiment: 10D cond 1D

dim(x)=9, dim(y)=1 — comparing LGD vs LGD-CM.

In [1]:
# ============================================================
# CONFIG — only this cell changes between notebooks
# ============================================================
EXPERIMENT_NAME   = "10D_cond_1D"
GLOBAL_SEED       = 42
FORCE_RETRAIN     = False

BASE_DIR          = "/content/conditional-matching-paper/simulations"
PARAMS_DIR        = f"{BASE_DIR}/params"
CHECKPOINT_DIR    = f"{BASE_DIR}/checkpoints/{EXPERIMENT_NAME}"
RESULTS_DIR       = f"{BASE_DIR}/results/{EXPERIMENT_NAME}"

# Architecture — Diffusion models
NBLOCKS           = 8
NUNITS            = 512

# Architecture — Consistency Model
NBLOCKS_CM        = 8
NUNITS_CM         = 512

# Training — Diffusion
NEPOCHS           = 40_000
BATCH_SIZE        = 4_096

# Training — Consistency Model
NEPOCHS_CM        = 40_000
BATCH_SIZE_CM     = 4_096

# Diffusion
DIFFUSION_STEPS   = 150

# Optimization
N_ATTEMP_OPTIM              = 25
NSAMPLES_IN_OPTIM_FOR_MMD   = 250
NUM_X_T_LGD                 = 3
NUM_X_T_LGD_CM              = 3

# GMM dimensions
CONDITION_ON      = 9   # dim(x)=9, dim(y)=1

In [2]:
!pip install flow_matching -q
!pip install POT -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.7/48.7 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 32.4 MB/s eta 0:00:00

In [3]:
import os, sys
from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF')
if hf_token:
    login(token=hf_token)
else:
    login()

if 'google.colab' in str(get_ipython()):
    import getpass
    !pip install -q diffusers transformers accelerate xformers
    !pip install -q scikit-learn matplotlib Pillow

    github_token = userdata.get('GITHUB')
    token = github_token if github_token else getpass.getpass("Enter your GitHub personal access token: ")

    repo_url  = f"https://{token}@github.com/orineo1/conditional-matching-paper.git"
    repo_name = "conditional-matching-paper"
    branch    = "adding-simu-compare"

    if not os.path.exists(repo_name):
        !git clone {repo_url}
    else:
        print(f"Repo '{repo_name}' already cloned — pulling latest...")
        !cd {repo_name} && git pull

    !cd {repo_name} && git checkout {branch}

# ── point Python at simulations/src where all .py modules live ──
src_path = f"/content/{repo_name}/simulations/src"
if src_path not in sys.path:
    sys.path.insert(0, src_path)

print(f"Branch: {branch}")
print(f"src path on sys.path: {src_path}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 50.3 MB/s eta 0:00:00
Cloning into 'conditional-matching-paper'...
remote: Enumerating objects: 6265, done.
remote: Counting objects: 100% (376/376), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 6265 (delta 364), reused 291 (delta 291), pack-reused 5889 (from 3)
Receiving objects: 100% (6265/6265), 1.28 GiB | 34.81 MiB/s, done.
Resolving deltas: 100% (1720/1720), done.
Updating files: 100% (255/255), done.
error: pathspec 'adding-simu-compare' did not match any file(s) known to git
Branch: adding-simu-compare
src path on sys.path: /content/conditional-matching-paper/simulations/src

In [4]:
import os, sys, time, json
import importlib
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
from functools import partial
from tqdm import trange

import Diffusion
import LossFunctions
import ConsistencyModels
import dist_utils
import Optimization
import experiment_utils
from ConsistencyModels import ConsistencyModeliCT
import evalModels

for mod in [Diffusion, LossFunctions, ConsistencyModels,
            dist_utils, Optimization, experiment_utils]:
    importlib.reload(mod)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(PARAMS_DIR,     exist_ok=True)
print("Imports done.")

Imports done.

In [5]:
env_info = experiment_utils.get_environment_info()
experiment_utils.print_environment_info(env_info)

============================================================
ENVIRONMENT INFO
============================================================
  timestamp: 2026-04-22T04:34:36.568785
  torch_version: 2.10.0+cu128
  cuda_available: True
  cuda_version: 12.8
  device_name: NVIDIA L4
  packages:
    torch: 2.10.0+cu128
    numpy: 2.0.2
    flow_matching: 1.0.10
    POT: 0.9.6.post1
    matplotlib: 3.10.0
    pandas: 2.2.2
    tqdm: 4.67.3
============================================================

In [6]:
experiment_utils.set_global_seed(GLOBAL_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

[Seed] All random seeds set to 42
Using device: cuda

## GMM Parameters

In [7]:
# ============================================================
# GMM PARAMETERS
# Priority:
#   1. Load from PARAMS_DIR  (shared across runs, committed to repo)
#   2. Load from RESULTS_DIR (fallback from a previous run)
#   3. Generate fresh and save to both dirs
#
# To force regeneration: set FORCE_REGENERATE_PARAMS = True
# ============================================================
FORCE_REGENERATE_PARAMS = False

def _load_params():
    """Try PARAMS_DIR first, then RESULTS_DIR."""
    loaded = experiment_utils.load_gmm_params(PARAMS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from PARAMS_DIR: {PARAMS_DIR}")
        return loaded
    loaded = experiment_utils.load_gmm_params(RESULTS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from RESULTS_DIR: {RESULTS_DIR}")
        return loaded
    return None

loaded = None if FORCE_REGENERATE_PARAMS else _load_params()

if loaded is not None:
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = loaded
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()
else:
    print("[GMM] Generating fresh parameters...")
    experiment_utils.set_global_seed(GLOBAL_SEED)   # seed generation for reproducibility
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = \
        dist_utils.get_param_mog_with_target(
            dim_data=10, num_components=4, device='cpu',
            conditional_modes=2, distanceOrScale="Distance"
        )
    mog_means, mog_variances, weights = dist_utils.filter_and_normalize(
        mog_means, mog_variances, weights, threshold=0.001
    )
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()

    # save to PARAMS_DIR (canonical, share across runs)
    experiment_utils.save_gmm_params(
        mu_list, Sigma_list, alpha,
        mog_means, mog_variances, weights, x_star,
        PARAMS_DIR, EXPERIMENT_NAME
    )


print(f"x_star = {x_star}")
print(f"Number of conditional modes after filtering: {len(mog_means)}")

[GMM] Parameters loaded from /content/conditional-matching-paper/simulations/params/10D_cond_1D_gmm_params.pt
[GMM] Loaded from PARAMS_DIR: /content/conditional-matching-paper/simulations/params
x_star = tensor([ -4.5404,   2.7114,   0.5513, -11.2950,   3.0335,  -0.6915,   4.1551,
         -1.2385,  -4.0147])
Number of conditional modes after filtering: 2

## Data

In [8]:
experiment_utils.set_global_seed(GLOBAL_SEED)
X = dist_utils.generate_mog_samples(25_000, mu_list, Sigma_list, alpha).float().to(device)

[Seed] All random seeds set to 42

## Train Models

### Consistency Model — P(Y|X=x)

In [9]:
experiment_utils.set_global_seed(GLOBAL_SEED)

B, C      = X.shape
nfeatures = C - CONDITION_ON
data_generator_cm = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha
)

Cos_ConsistencyModeliCT = ConsistencyModeliCT(
    nfeatures=nfeatures, condition_on=CONDITION_ON,
    nunits=NUNITS_CM, depth=NBLOCKS_CM
)

_loaded_cm = experiment_utils.load_model_checkpoint(
    Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_cm:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    Cos_ConsistencyModeliCT.train_model(
        X=None, nepochs=NEPOCHS_CM, batch_size=BATCH_SIZE_CM,
        device=device, condition=CONDITION_ON,
        data_generator=data_generator_cm, use_improved_training=True
    )
    experiment_utils.save_model_checkpoint(
        Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] CM loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_CM_seed42.pt

### Diffusion — P(Y|X=x)

In [10]:
experiment_utils.set_global_seed(GLOBAL_SEED)

X_train   = dist_utils.generate_mog_samples(1_000, mu_list, Sigma_list, alpha).float().to(device)
nfeatures = X_train.shape[1]

data_generator_diff_cond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha, kernel_func=None
)

model_cond = Diffusion.DiffusionModel(
    nfeatures=nfeatures, nblocks=NBLOCKS, nunits=NUNITS,
    condition=True, condition_on=CONDITION_ON,
    diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_cond = experiment_utils.load_model_checkpoint(
    model_cond, "Diffusion_cond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_cond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_cond.train_model(
        None, data_generator=data_generator_diff_cond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_cond, "Diffusion_cond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_cond loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt

### Diffusion — P(X=x)

In [11]:
experiment_utils.set_global_seed(GLOBAL_SEED)

data_generator_diff_uncond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha,
    kernel_func=lambda X: X[:, :CONDITION_ON]
)

model_uncond = Diffusion.DiffusionModel(
    nfeatures=CONDITION_ON, nblocks=NBLOCKS, nunits=NUNITS,
    condition=False, diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_uncond = experiment_utils.load_model_checkpoint(
    model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_uncond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_uncond.train_model(
        None, data_generator=data_generator_diff_uncond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_uncond loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt

## Optimize

### LGD

In [12]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_list = []
l2_gmm_LGD_list   = []
l2_x_LGD_list     = []
lgd_times         = []
final_loss_LGD    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, model_cond, mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        num_x_t=NUM_X_T_LGD
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_times.append(end_time - start_time)
    final_loss_LGD.append(final_loss)
    best_x_t_LGD_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_list.append(l2_gmm)
    l2_x_LGD_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  0%|          | 0/25 [00:00<?, ?it/s]/content/conditional-matching-paper/simulations/src/dist_utils.py:466: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  exponent = -0.5 * diff.T @ Sigma_22_inv @ diff
  4%|▍         | 1/25 [09:22<3:45:11, 562.99s/it]

[1] seed=42 | L2 GMM: 0.504536 | L2 to x*: 18.043385

  8%|▊         | 2/25 [18:40<3:34:28, 559.48s/it]

[2] seed=43 | L2 GMM: 0.953849 | L2 to x*: 16.651876

 12%|█▏        | 3/25 [27:54<3:24:23, 557.42s/it]

[3] seed=44 | L2 GMM: 0.526375 | L2 to x*: 33.577255

 16%|█▌        | 4/25 [37:12<3:15:09, 557.58s/it]

[4] seed=45 | L2 GMM: 0.720300 | L2 to x*: 7.328388

 20%|██        | 5/25 [46:29<3:05:44, 557.25s/it]

[5] seed=46 | L2 GMM: 0.403975 | L2 to x*: 35.415257

 24%|██▍       | 6/25 [55:45<2:56:22, 556.99s/it]

[6] seed=47 | L2 GMM: 0.434794 | L2 to x*: 114.595772

 28%|██▊       | 7/25 [1:05:03<2:47:06, 557.01s/it]

[7] seed=48 | L2 GMM: 0.471313 | L2 to x*: 34.947300

 32%|███▏      | 8/25 [1:14:21<2:37:55, 557.41s/it]

[8] seed=49 | L2 GMM: 0.723155 | L2 to x*: 11.544769

 36%|███▌      | 9/25 [1:23:38<2:28:35, 557.21s/it]

[9] seed=50 | L2 GMM: 0.492345 | L2 to x*: 19.811050

 40%|████      | 10/25 [1:32:54<2:19:15, 557.01s/it]

[10] seed=51 | L2 GMM: 0.502676 | L2 to x*: 10.653556

 44%|████▍     | 11/25 [1:42:11<2:09:56, 556.91s/it]

[11] seed=52 | L2 GMM: 0.723164 | L2 to x*: 9.390922

 48%|████▊     | 12/25 [1:51:30<2:00:47, 557.51s/it]

[12] seed=53 | L2 GMM: 0.731437 | L2 to x*: 15.742133

 52%|█████▏    | 13/25 [2:00:47<1:51:28, 557.34s/it]

[13] seed=54 | L2 GMM: 0.822126 | L2 to x*: 17.068787

 56%|█████▌    | 14/25 [2:10:01<1:42:00, 556.44s/it]

[14] seed=55 | L2 GMM: 0.504536 | L2 to x*: 13.247545

 60%|██████    | 15/25 [2:19:10<1:32:20, 554.09s/it]

[15] seed=56 | L2 GMM: 0.498338 | L2 to x*: 25.312939

 64%|██████▍   | 16/25 [2:28:20<1:22:57, 553.09s/it]

[16] seed=57 | L2 GMM: 0.504536 | L2 to x*: 8.582930

 68%|██████▊   | 17/25 [2:37:31<1:13:37, 552.19s/it]

[17] seed=58 | L2 GMM: 0.584269 | L2 to x*: 17.398827

 72%|███████▏  | 18/25 [2:46:41<1:04:22, 551.78s/it]

[18] seed=59 | L2 GMM: 0.723915 | L2 to x*: 4.889707

 76%|███████▌  | 19/25 [2:55:53<55:10, 551.79s/it]

[19] seed=60 | L2 GMM: 0.723164 | L2 to x*: 96.392426

 80%|████████  | 20/25 [3:05:03<45:56, 551.30s/it]

[20] seed=61 | L2 GMM: 0.738438 | L2 to x*: 10.641582

 84%|████████▍ | 21/25 [3:14:14<36:44, 551.07s/it]

[21] seed=62 | L2 GMM: 0.290794 | L2 to x*: 18.144457

 88%|████████▊ | 22/25 [3:23:23<27:31, 550.59s/it]

[22] seed=63 | L2 GMM: 0.605728 | L2 to x*: 14.450094

 92%|█████████▏| 23/25 [3:32:35<18:21, 550.79s/it]

[23] seed=64 | L2 GMM: 0.504535 | L2 to x*: 6.369512

 96%|█████████▌| 24/25 [3:41:47<09:11, 551.20s/it]

[24] seed=65 | L2 GMM: 0.169670 | L2 to x*: 34.133354

100%|██████████| 25/25 [3:50:58<00:00, 554.34s/it]

[25] seed=66 | L2 GMM: 0.309181 | L2 to x*: 20.047318

### LGD-CM

In [13]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_CM_list = []
l2_gmm_LGD_CM_list   = []
l2_x_LGD_CM_list     = []
lgd_cm_times         = []
final_loss_LGD_CM    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, Cos_ConsistencyModeliCT,
        mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        CM=True, FLAG=False, num_x_t=NUM_X_T_LGD_CM
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_cm_times.append(end_time - start_time)
    final_loss_LGD_CM.append(final_loss)
    best_x_t_LGD_CM_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_CM_list.append(l2_gmm)
    l2_x_LGD_CM_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [00:25<10:07, 25.31s/it]

[1] seed=42 | L2 GMM: 0.368064 | L2 to x*: 10.244242

  8%|▊         | 2/25 [00:50<09:37, 25.13s/it]

[2] seed=43 | L2 GMM: 0.296259 | L2 to x*: 4.526285

 12%|█▏        | 3/25 [01:15<09:12, 25.13s/it]

[3] seed=44 | L2 GMM: 0.320303 | L2 to x*: 3.076661

 16%|█▌        | 4/25 [01:40<08:49, 25.23s/it]

[4] seed=45 | L2 GMM: 0.446716 | L2 to x*: 10.949749

 20%|██        | 5/25 [02:06<08:26, 25.32s/it]

[5] seed=46 | L2 GMM: 0.733155 | L2 to x*: 4.755563

 24%|██▍       | 6/25 [02:31<08:03, 25.43s/it]

[6] seed=47 | L2 GMM: 0.039597 | L2 to x*: 2.573688

 28%|██▊       | 7/25 [02:57<07:39, 25.51s/it]

[7] seed=48 | L2 GMM: 0.504485 | L2 to x*: 4.413910

 32%|███▏      | 8/25 [03:23<07:14, 25.56s/it]

[8] seed=49 | L2 GMM: 0.370588 | L2 to x*: 22.810047

 36%|███▌      | 9/25 [03:48<06:48, 25.53s/it]

[9] seed=50 | L2 GMM: 0.391209 | L2 to x*: 31.971296

 40%|████      | 10/25 [04:14<06:23, 25.59s/it]

[10] seed=51 | L2 GMM: 0.133017 | L2 to x*: 40.837502

 44%|████▍     | 11/25 [04:40<05:57, 25.57s/it]

[11] seed=52 | L2 GMM: 0.117608 | L2 to x*: 3.680158

 48%|████▊     | 12/25 [05:05<05:32, 25.59s/it]

[12] seed=53 | L2 GMM: 0.696737 | L2 to x*: 7.248093

 52%|█████▏    | 13/25 [05:31<05:06, 25.55s/it]

[13] seed=54 | L2 GMM: 0.197604 | L2 to x*: 2.357128

 56%|█████▌    | 14/25 [05:56<04:41, 25.57s/it]

[14] seed=55 | L2 GMM: 0.315055 | L2 to x*: 4.180271

 60%|██████    | 15/25 [06:22<04:15, 25.56s/it]

[15] seed=56 | L2 GMM: 0.415371 | L2 to x*: 5.068972

 64%|██████▍   | 16/25 [06:48<03:50, 25.61s/it]

[16] seed=57 | L2 GMM: 0.504536 | L2 to x*: 15.849276

 68%|██████▊   | 17/25 [07:13<03:24, 25.61s/it]

[17] seed=58 | L2 GMM: 0.153264 | L2 to x*: 30.828419

 72%|███████▏  | 18/25 [07:39<02:59, 25.60s/it]

[18] seed=59 | L2 GMM: 0.113924 | L2 to x*: 3.327401

 76%|███████▌  | 19/25 [08:04<02:33, 25.65s/it]

[19] seed=60 | L2 GMM: 0.439836 | L2 to x*: 2.749405

 80%|████████  | 20/25 [08:30<02:07, 25.59s/it]

[20] seed=61 | L2 GMM: 0.173525 | L2 to x*: 32.066994

 84%|████████▍ | 21/25 [08:56<01:42, 25.61s/it]

[21] seed=62 | L2 GMM: 0.953682 | L2 to x*: 9.966556

 88%|████████▊ | 22/25 [09:21<01:16, 25.64s/it]

[22] seed=63 | L2 GMM: 0.015464 | L2 to x*: 2.837351

 92%|█████████▏| 23/25 [09:47<00:51, 25.69s/it]

[23] seed=64 | L2 GMM: 0.125591 | L2 to x*: 2.849772

 96%|█████████▌| 24/25 [10:13<00:25, 25.75s/it]

[24] seed=65 | L2 GMM: 0.292312 | L2 to x*: 2.747335

100%|██████████| 25/25 [10:39<00:00, 25.57s/it]

[25] seed=66 | L2 GMM: 0.243391 | L2 to x*: 2.185739

## Results

In [14]:
rows = [
    experiment_utils.summary_row("LGD",    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.summary_row("LGD-CM", l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df = pd.DataFrame(rows).set_index("Method")
display(df)

rows_top10 = [
    experiment_utils.top10_stats("LGD",    final_loss_LGD,    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.top10_stats("LGD-CM", final_loss_LGD_CM, l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df_top10 = pd.DataFrame(rows_top10).set_index("Method")
display(df_top10)

,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s)
Method,,,,,,
LGD,0.5667,0.1766,24.5752,25.5551,554.32,3.65
LGD-CM,0.3345,0.2214,10.5641,11.3399,25.56,0.20

,Loss mean,Loss std,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s),Top-k selected
Method,,,,,,,,,
LGD,0.2737,0.1326,0.4251,0.1229,24.7371,8.8858,552.87,3.01,10
LGD-CM,0.1006,0.0737,0.1946,0.1384,4.2934,3.9070,25.60,0.23,10

In [15]:
def to_python(val):
    if isinstance(val, torch.Tensor):
        return val.detach().cpu().tolist()
    if isinstance(val, np.ndarray):
        return val.tolist()
    if hasattr(val, "item"):
        return val.item()
    return val

results = {
    "experiment":  EXPERIMENT_NAME,
    "seed":        GLOBAL_SEED,
    "environment": env_info,
    "LGD": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_list],
        "final_loss": [to_python(l) for l in final_loss_LGD],
        "l2_gmm":     l2_gmm_LGD_list,
        "l2_x":       l2_x_LGD_list,
        "times":      lgd_times,
    },
    "LGD-CM": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_CM_list],
        "final_loss": [to_python(l) for l in final_loss_LGD_CM],
        "l2_gmm":     l2_gmm_LGD_CM_list,
        "l2_x":       l2_x_LGD_CM_list,
        "times":      lgd_cm_times,
    },
    "meta": {
        "n_attemp_optim":            N_ATTEMP_OPTIM,
        "nsamples_in_optim_for_mmd": NSAMPLES_IN_OPTIM_FOR_MMD,
        "x_star":                    to_python(x_star),
    },
}

path = os.path.join(RESULTS_DIR, f"{EXPERIMENT_NAME}_results_seed{GLOBAL_SEED}.json")
with open(path, "w") as f:
    json.dump(results, f, indent=2)
print(f"Results saved to {path}")

Results saved to /content/conditional-matching-paper/simulations/results/10D_cond_1D/10D_cond_1D_results_seed42.json

In [16]:
from google.colab import files
import zipfile

# 1. Download the Results JSON
print(f"Downloading results: {path}")
files.download(path)

# 2. Zip the Checkpoints directory and download it
zip_path = f"/content/{EXPERIMENT_NAME}_checkpoints.zip"
print(f"Zipping checkpoints to {zip_path}...")

with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_in_dir in os.walk(CHECKPOINT_DIR):
        for file in files_in_dir:
            file_full_path = os.path.join(root, file)
            # Store with a relative path inside the zip
            arcname = os.path.relpath(file_full_path, CHECKPOINT_DIR)
            zipf.write(file_full_path, arcname)

print("Downloading checkpoints zip...")
files.download(zip_path)

Downloading results: /content/conditional-matching-paper/simulations/results/10D_cond_1D/10D_cond_1D_results_seed42.json

Zipping checkpoints to /content/10D_cond_1D_checkpoints.zip...
Downloading checkpoints zip...