# Experiment: 10D cond 1D

dim(x)=9, dim(y)=1 — comparing LGD vs LGD-CM.

In [10]:
# ============================================================
# CONFIG — only this cell changes between notebooks
# ============================================================
EXPERIMENT_NAME   = "10D_cond_1D"
GLOBAL_SEED       = 42
FORCE_RETRAIN     = False

BASE_DIR          = "/content/conditional-matching-paper/simulations"
PARAMS_DIR        = f"{BASE_DIR}/params"
CHECKPOINT_DIR    = f"{BASE_DIR}/checkpoints/{EXPERIMENT_NAME}"
RESULTS_DIR       = f"{BASE_DIR}/results/{EXPERIMENT_NAME}"

# Architecture — Diffusion models
NBLOCKS           = 8
NUNITS            = 512

# Architecture — Consistency Model
NBLOCKS_CM        = 8
NUNITS_CM         = 512

# Training — Diffusion
NEPOCHS           = 40_000
BATCH_SIZE        = 4_096

# Training — Consistency Model
NEPOCHS_CM        = 40_000
BATCH_SIZE_CM     = 4_096

# Diffusion
DIFFUSION_STEPS   = 150

# Optimization
N_ATTEMP_OPTIM              = 25
NSAMPLES_IN_OPTIM_FOR_MMD   = 250
NUM_X_T_LGD                 = 5
NUM_X_T_LGD_CM              = 5

# GMM dimensions
CONDITION_ON      = 9   # dim(x)=9, dim(y)=1

In [2]:
!pip install flow_matching -q
!pip install POT -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.7/48.7 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 86.1 MB/s eta 0:00:00

In [3]:
import os, sys
from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF')
if hf_token:
    login(token=hf_token)
else:
    login()

if 'google.colab' in str(get_ipython()):
    import getpass
    !pip install -q diffusers transformers accelerate xformers
    !pip install -q scikit-learn matplotlib Pillow

    github_token = userdata.get('GITHUB')
    token = github_token if github_token else getpass.getpass("Enter your GitHub personal access token: ")

    repo_url  = f"https://{token}@github.com/orineo1/conditional-matching-paper.git"
    repo_name = "conditional-matching-paper"
    branch    = "adding-simu-compare"

    if not os.path.exists(repo_name):
        !git clone {repo_url}
    else:
        print(f"Repo '{repo_name}' already cloned — pulling latest...")
        !cd {repo_name} && git pull

    !cd {repo_name} && git checkout {branch}

# ── point Python at simulations/src where all .py modules live ──
src_path = f"/content/{repo_name}/simulations/src"
if src_path not in sys.path:
    sys.path.insert(0, src_path)

print(f"Branch: {branch}")
print(f"src path on sys.path: {src_path}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 114.1 MB/s eta 0:00:00
Cloning into 'conditional-matching-paper'...
remote: Enumerating objects: 6133, done.
remote: Counting objects: 100% (387/387), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 6133 (delta 368), reused 299 (delta 293), pack-reused 5746 (from 2)
Receiving objects: 100% (6133/6133), 1.20 GiB | 17.25 MiB/s, done.
Resolving deltas: 100% (1639/1639), done.
error: pathspec 'adding-simu-compare' did not match any file(s) known to git
Branch: adding-simu-compare
src path on sys.path: /content/conditional-matching-paper/simulations/src

In [4]:
import os, sys, time, json
import importlib
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
from functools import partial
from tqdm import trange

import Diffusion
import LossFunctions
import ConsistencyModels
import dist_utils
import Optimization
import experiment_utils
from ConsistencyModels import ConsistencyModeliCT
import evalModels

for mod in [Diffusion, LossFunctions, ConsistencyModels,
            dist_utils, Optimization, experiment_utils]:
    importlib.reload(mod)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(PARAMS_DIR,     exist_ok=True)
print("Imports done.")

Imports done.

In [5]:
env_info = experiment_utils.get_environment_info()
experiment_utils.print_environment_info(env_info)

============================================================
ENVIRONMENT INFO
============================================================
  timestamp: 2026-04-20T05:16:53.624648
  torch_version: 2.10.0+cu128
  cuda_available: True
  cuda_version: 12.8
  device_name: NVIDIA L4
  packages:
    torch: 2.10.0+cu128
    numpy: 2.0.2
    flow_matching: 1.0.10
    POT: 0.9.6.post1
    matplotlib: 3.10.0
    pandas: 2.2.2
    tqdm: 4.67.3
============================================================

In [6]:
experiment_utils.set_global_seed(GLOBAL_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

[Seed] All random seeds set to 42
Using device: cuda

## GMM Parameters

In [7]:
# ============================================================
# GMM PARAMETERS
# Priority:
#   1. Load from PARAMS_DIR  (shared across runs, committed to repo)
#   2. Load from RESULTS_DIR (fallback from a previous run)
#   3. Generate fresh and save to both dirs
#
# To force regeneration: set FORCE_REGENERATE_PARAMS = True
# ============================================================
FORCE_REGENERATE_PARAMS = False

def _load_params():
    """Try PARAMS_DIR first, then RESULTS_DIR."""
    loaded = experiment_utils.load_gmm_params(PARAMS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from PARAMS_DIR: {PARAMS_DIR}")
        return loaded
    loaded = experiment_utils.load_gmm_params(RESULTS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from RESULTS_DIR: {RESULTS_DIR}")
        return loaded
    return None

loaded = None if FORCE_REGENERATE_PARAMS else _load_params()

if loaded is not None:
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = loaded
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()
else:
    print("[GMM] Generating fresh parameters...")
    experiment_utils.set_global_seed(GLOBAL_SEED)   # seed generation for reproducibility
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = \
        dist_utils.get_param_mog_with_target(
            dim_data=10, num_components=4, device='cpu',
            conditional_modes=2, distanceOrScale="Distance"
        )
    mog_means, mog_variances, weights = dist_utils.filter_and_normalize(
        mog_means, mog_variances, weights, threshold=0.001
    )
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()

    # save to PARAMS_DIR (canonical, share across runs)
    experiment_utils.save_gmm_params(
        mu_list, Sigma_list, alpha,
        mog_means, mog_variances, weights, x_star,
        PARAMS_DIR, EXPERIMENT_NAME
    )


print(f"x_star = {x_star}")
print(f"Number of conditional modes after filtering: {len(mog_means)}")

[GMM] Parameters loaded from /content/conditional-matching-paper/simulations/params/10D_cond_1D_gmm_params.pt
[GMM] Loaded from PARAMS_DIR: /content/conditional-matching-paper/simulations/params
x_star = tensor([ -4.5404,   2.7114,   0.5513, -11.2950,   3.0335,  -0.6915,   4.1551,
         -1.2385,  -4.0147])
Number of conditional modes after filtering: 2

## Data

In [8]:
experiment_utils.set_global_seed(GLOBAL_SEED)
X = dist_utils.generate_mog_samples(25_000, mu_list, Sigma_list, alpha).float().to(device)

[Seed] All random seeds set to 42

## Train Models

### Consistency Model — P(Y|X=x)

In [11]:
experiment_utils.set_global_seed(GLOBAL_SEED)

B, C      = X.shape
nfeatures = C - CONDITION_ON
data_generator_cm = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha
)

Cos_ConsistencyModeliCT = ConsistencyModeliCT(
    nfeatures=nfeatures, condition_on=CONDITION_ON,
    nunits=NUNITS_CM, depth=NBLOCKS_CM
)

_loaded_cm = experiment_utils.load_model_checkpoint(
    Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_cm:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    Cos_ConsistencyModeliCT.train_model(
        X=None, nepochs=NEPOCHS_CM, batch_size=BATCH_SIZE_CM,
        device=device, condition=CONDITION_ON,
        data_generator=data_generator_cm, use_improved_training=True
    )
    experiment_utils.save_model_checkpoint(
        Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] CM loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_CM_seed42.pt

### Diffusion — P(Y|X=x)

In [12]:
experiment_utils.set_global_seed(GLOBAL_SEED)

X_train   = dist_utils.generate_mog_samples(1_000, mu_list, Sigma_list, alpha).float().to(device)
nfeatures = X_train.shape[1]

data_generator_diff_cond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha, kernel_func=None
)

model_cond = Diffusion.DiffusionModel(
    nfeatures=nfeatures, nblocks=NBLOCKS, nunits=NUNITS,
    condition=True, condition_on=CONDITION_ON,
    diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_cond = experiment_utils.load_model_checkpoint(
    model_cond, "Diffusion_cond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_cond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_cond.train_model(
        None, data_generator=data_generator_diff_cond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_cond, "Diffusion_cond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] No checkpoint found for Diffusion_cond at /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt
[Seed] All random seeds set to 42

loss: 0.169880: 100%|██████████| 40000/40000 [4:04:48<00:00,  2.72it/s]

[Checkpoint] Diffusion_cond saved to /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt

### Diffusion — P(X=x)

In [13]:
experiment_utils.set_global_seed(GLOBAL_SEED)

data_generator_diff_uncond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha,
    kernel_func=lambda X: X[:, :CONDITION_ON]
)

model_uncond = Diffusion.DiffusionModel(
    nfeatures=CONDITION_ON, nblocks=NBLOCKS, nunits=NUNITS,
    condition=False, diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_uncond = experiment_utils.load_model_checkpoint(
    model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_uncond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_uncond.train_model(
        None, data_generator=data_generator_diff_uncond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] No checkpoint found for Diffusion_uncond at /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt
[Seed] All random seeds set to 42

loss: 0.683576: 100%|██████████| 40000/40000 [3:51:33<00:00,  2.88it/s]

[Checkpoint] Diffusion_uncond saved to /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt

## Optimize

### LGD

In [14]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_list = []
l2_gmm_LGD_list   = []
l2_x_LGD_list     = []
lgd_times         = []
final_loss_LGD    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, model_cond, mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        num_x_t=NUM_X_T_LGD
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_times.append(end_time - start_time)
    final_loss_LGD.append(final_loss)
    best_x_t_LGD_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_list.append(l2_gmm)
    l2_x_LGD_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  0%|          | 0/25 [00:00<?, ?it/s]/content/conditional-matching-paper/simulations/src/dist_utils.py:466: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  exponent = -0.5 * diff.T @ Sigma_22_inv @ diff
  4%|▍         | 1/25 [09:09<3:39:51, 549.66s/it]

[1] seed=42 | L2 GMM: 0.714958 | L2 to x*: 10.176175

  8%|▊         | 2/25 [18:17<3:30:13, 548.41s/it]

[2] seed=43 | L2 GMM: 0.953853 | L2 to x*: 16.770523

 12%|█▏        | 3/25 [27:23<3:20:44, 547.48s/it]

[3] seed=44 | L2 GMM: 0.609890 | L2 to x*: 18.670069

 16%|█▌        | 4/25 [36:31<3:11:40, 547.62s/it]

[4] seed=45 | L2 GMM: 0.441064 | L2 to x*: 21.847754

 20%|██        | 5/25 [45:40<3:02:39, 547.97s/it]

[5] seed=46 | L2 GMM: 0.398815 | L2 to x*: 35.415066

 24%|██▍       | 6/25 [54:48<2:53:35, 548.21s/it]

[6] seed=47 | L2 GMM: 0.434794 | L2 to x*: 114.448479

 28%|██▊       | 7/25 [1:03:56<2:44:22, 547.94s/it]

[7] seed=48 | L2 GMM: 0.483157 | L2 to x*: 34.829544

 32%|███▏      | 8/25 [1:13:01<2:35:03, 547.25s/it]

[8] seed=49 | L2 GMM: 0.724902 | L2 to x*: 6.156953

 36%|███▌      | 9/25 [1:22:09<2:25:58, 547.43s/it]

[9] seed=50 | L2 GMM: 0.504536 | L2 to x*: 19.700600

 40%|████      | 10/25 [1:31:17<2:16:54, 547.65s/it]

[10] seed=51 | L2 GMM: 0.562355 | L2 to x*: 9.730501

 44%|████▍     | 11/25 [1:40:27<2:07:53, 548.14s/it]

[11] seed=52 | L2 GMM: 0.271245 | L2 to x*: 4.001086

 48%|████▊     | 12/25 [1:49:33<1:58:37, 547.48s/it]

[12] seed=53 | L2 GMM: 0.814117 | L2 to x*: 16.372339

 52%|█████▏    | 13/25 [1:58:41<1:49:32, 547.69s/it]

[13] seed=54 | L2 GMM: 0.503492 | L2 to x*: 12.359115

 56%|█████▌    | 14/25 [2:07:45<1:40:14, 546.81s/it]

[14] seed=55 | L2 GMM: 0.866037 | L2 to x*: 12.004896

 60%|██████    | 15/25 [2:16:54<1:31:14, 547.43s/it]

[15] seed=56 | L2 GMM: 0.504227 | L2 to x*: 9.897902

 64%|██████▍   | 16/25 [2:26:02<1:22:07, 547.50s/it]

[16] seed=57 | L2 GMM: 0.728456 | L2 to x*: 8.728290

 68%|██████▊   | 17/25 [2:35:07<1:12:53, 546.73s/it]

[17] seed=58 | L2 GMM: 0.504536 | L2 to x*: 17.105328

 72%|███████▏  | 18/25 [2:44:16<1:03:51, 547.34s/it]

[18] seed=59 | L2 GMM: 0.953854 | L2 to x*: 7.210229

 76%|███████▌  | 19/25 [2:53:21<54:40, 546.67s/it]

[19] seed=60 | L2 GMM: 0.723164 | L2 to x*: 96.400070

 80%|████████  | 20/25 [3:02:28<45:34, 546.86s/it]

[20] seed=61 | L2 GMM: 0.489063 | L2 to x*: 10.437963

 84%|████████▍ | 21/25 [3:11:34<36:26, 546.52s/it]

[21] seed=62 | L2 GMM: 0.504536 | L2 to x*: 21.545300

 88%|████████▊ | 22/25 [3:20:41<27:20, 546.73s/it]

[22] seed=63 | L2 GMM: 0.156708 | L2 to x*: 9.232402

 92%|█████████▏| 23/25 [3:29:48<18:13, 546.69s/it]

[23] seed=64 | L2 GMM: 0.315082 | L2 to x*: 6.735410

 96%|█████████▌| 24/25 [3:38:54<09:06, 546.62s/it]

[24] seed=65 | L2 GMM: 0.181768 | L2 to x*: 34.354500

100%|██████████| 25/25 [3:48:01<00:00, 547.28s/it]

[25] seed=66 | L2 GMM: 0.864951 | L2 to x*: 9.938586

### LGD-CM

In [15]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_CM_list = []
l2_gmm_LGD_CM_list   = []
l2_x_LGD_CM_list     = []
lgd_cm_times         = []
final_loss_LGD_CM    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, Cos_ConsistencyModeliCT,
        mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        CM=True, FLAG=False, num_x_t=NUM_X_T_LGD_CM
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_cm_times.append(end_time - start_time)
    final_loss_LGD_CM.append(final_loss)
    best_x_t_LGD_CM_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_CM_list.append(l2_gmm)
    l2_x_LGD_CM_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [00:38<15:31, 38.81s/it]

[1] seed=42 | L2 GMM: 0.309481 | L2 to x*: 3.016690

  8%|▊         | 2/25 [01:17<14:52, 38.80s/it]

[2] seed=43 | L2 GMM: 0.182874 | L2 to x*: 31.081961

 12%|█▏        | 3/25 [01:56<14:15, 38.89s/it]

[3] seed=44 | L2 GMM: 0.308499 | L2 to x*: 3.456086

 16%|█▌        | 4/25 [02:35<13:38, 38.99s/it]

[4] seed=45 | L2 GMM: 0.296070 | L2 to x*: 2.168507

 20%|██        | 5/25 [03:14<13:01, 39.06s/it]

[5] seed=46 | L2 GMM: 0.247745 | L2 to x*: 7.472059

 24%|██▍       | 6/25 [03:53<12:19, 38.94s/it]

[6] seed=47 | L2 GMM: 0.245424 | L2 to x*: 4.293778

 28%|██▊       | 7/25 [04:32<11:40, 38.89s/it]

[7] seed=48 | L2 GMM: 0.229549 | L2 to x*: 2.769571

 32%|███▏      | 8/25 [05:11<10:59, 38.79s/it]

[8] seed=49 | L2 GMM: 0.049202 | L2 to x*: 2.048836

 36%|███▌      | 9/25 [05:49<10:21, 38.84s/it]

[9] seed=50 | L2 GMM: 0.768317 | L2 to x*: 14.752969

 40%|████      | 10/25 [06:29<09:44, 38.98s/it]

[10] seed=51 | L2 GMM: 0.946945 | L2 to x*: 17.335722

 44%|████▍     | 11/25 [07:08<09:05, 38.95s/it]

[11] seed=52 | L2 GMM: 0.159021 | L2 to x*: 31.238979

 48%|████▊     | 12/25 [07:46<08:24, 38.83s/it]

[12] seed=53 | L2 GMM: 0.877052 | L2 to x*: 16.647282

 52%|█████▏    | 13/25 [08:25<07:45, 38.83s/it]

[13] seed=54 | L2 GMM: 0.721831 | L2 to x*: 21.850971

 56%|█████▌    | 14/25 [09:04<07:07, 38.83s/it]

[14] seed=55 | L2 GMM: 0.800793 | L2 to x*: 11.387438

 60%|██████    | 15/25 [09:43<06:28, 38.86s/it]

[15] seed=56 | L2 GMM: 0.154474 | L2 to x*: 2.776284

 64%|██████▍   | 16/25 [10:22<05:50, 38.92s/it]

[16] seed=57 | L2 GMM: 0.351887 | L2 to x*: 3.884019

 68%|██████▊   | 17/25 [11:01<05:11, 38.97s/it]

[17] seed=58 | L2 GMM: 0.174506 | L2 to x*: 32.690422

 72%|███████▏  | 18/25 [11:40<04:33, 39.06s/it]

[18] seed=59 | L2 GMM: 0.026220 | L2 to x*: 2.527642

 76%|███████▌  | 19/25 [12:19<03:54, 39.01s/it]

[19] seed=60 | L2 GMM: 0.129242 | L2 to x*: 3.267677

 80%|████████  | 20/25 [12:58<03:14, 38.94s/it]

[20] seed=61 | L2 GMM: 0.430074 | L2 to x*: 7.820604

 84%|████████▍ | 21/25 [13:36<02:35, 38.84s/it]

[21] seed=62 | L2 GMM: 0.703950 | L2 to x*: 19.199358

 88%|████████▊ | 22/25 [14:15<01:56, 38.77s/it]

[22] seed=63 | L2 GMM: 0.700891 | L2 to x*: 13.306082

 92%|█████████▏| 23/25 [14:54<01:17, 38.76s/it]

[23] seed=64 | L2 GMM: 0.182112 | L2 to x*: 2.348372

 96%|█████████▌| 24/25 [15:33<00:38, 38.80s/it]

[24] seed=65 | L2 GMM: 0.061838 | L2 to x*: 3.026414

100%|██████████| 25/25 [16:11<00:00, 38.87s/it]

[25] seed=66 | L2 GMM: 0.038853 | L2 to x*: 3.348599

## Results

In [16]:
rows = [
    experiment_utils.summary_row("LGD",    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.summary_row("LGD-CM", l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df = pd.DataFrame(rows).set_index("Method")
display(df)

rows_top10 = [
    experiment_utils.top10_stats("LGD",    final_loss_LGD,    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.top10_stats("LGD-CM", final_loss_LGD_CM, l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df_top10 = pd.DataFrame(rows_top10).set_index("Method")
display(df_top10)

,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s)
Method,,,,,,
LGD,0.5684,0.2191,22.5628,26.0351,547.26,1.34
LGD-CM,0.3639,0.2848,10.5487,9.8299,38.86,0.20

,Loss mean,Loss std,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s),Top-k selected
Method,,,,,,,,,
LGD,0.2806,0.1595,0.4341,0.1132,20.8968,10.5957,547.33,1.25,10
LGD-CM,0.0900,0.0597,0.1413,0.0912,2.8576,0.6334,38.85,0.20,10

In [17]:
def to_python(val):
    if isinstance(val, torch.Tensor):
        return val.detach().cpu().tolist()
    if isinstance(val, np.ndarray):
        return val.tolist()
    if hasattr(val, "item"):
        return val.item()
    return val

results = {
    "experiment":  EXPERIMENT_NAME,
    "seed":        GLOBAL_SEED,
    "environment": env_info,
    "LGD": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_list],
        "final_loss": [to_python(l) for l in final_loss_LGD],
        "l2_gmm":     l2_gmm_LGD_list,
        "l2_x":       l2_x_LGD_list,
        "times":      lgd_times,
    },
    "LGD-CM": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_CM_list],
        "final_loss": [to_python(l) for l in final_loss_LGD_CM],
        "l2_gmm":     l2_gmm_LGD_CM_list,
        "l2_x":       l2_x_LGD_CM_list,
        "times":      lgd_cm_times,
    },
    "meta": {
        "n_attemp_optim":            N_ATTEMP_OPTIM,
        "nsamples_in_optim_for_mmd": NSAMPLES_IN_OPTIM_FOR_MMD,
        "x_star":                    to_python(x_star),
    },
}

path = os.path.join(RESULTS_DIR, f"{EXPERIMENT_NAME}_results_seed{GLOBAL_SEED}.json")
with open(path, "w") as f:
    json.dump(results, f, indent=2)
print(f"Results saved to {path}")

Results saved to /content/conditional-matching-paper/simulations/results/10D_cond_1D/10D_cond_1D_results_seed42.json