# Experiment: 5D cond 1D

dim(x)=4, dim(y)=1 — comparing LGD vs LGD-CM.

In [1]:
import os
# ============================================================
# CONFIG — only this cell changes between notebooks
# ============================================================
EXPERIMENT_NAME   = "5D_cond_1D"
GLOBAL_SEED       = 42
FORCE_RETRAIN     = False

BASE_DIR = os.path.normpath(os.path.join(os.getcwd(), ".."))
PARAMS_DIR        = f"{BASE_DIR}/params"
CHECKPOINT_DIR    = f"{BASE_DIR}/checkpoints/{EXPERIMENT_NAME}"
RESULTS_DIR       = f"{BASE_DIR}/results/{EXPERIMENT_NAME}"

# Architecture — Diffusion models
NBLOCKS           = 6
NUNITS            = 512

# Architecture — Consistency Model
NBLOCKS_CM        = 6
NUNITS_CM         = 512

# Training — Diffusion
NEPOCHS           = 40_000#20_000
BATCH_SIZE        = 4_096#512

# Training — Consistency Model
NEPOCHS_CM        = 40_000
BATCH_SIZE_CM     = 4_096

# Diffusion
DIFFUSION_STEPS   = 100

# Optimization
N_ATTEMP_OPTIM              = 25
NSAMPLES_IN_OPTIM_FOR_MMD   = 250
NUM_X_T_LGD                 = 5
NUM_X_T_LGD_CM              = 5

# GMM dimensions
CONDITION_ON      = 4   # dim(x)=4, dim(y)=1

In [ ]:
import os, sys

# ── point Python at simulations/src where all .py modules live ──
src_path = os.path.join(os.path.dirname(os.path.abspath("__file__")), "..", "src")
src_path = os.path.normpath(src_path)
if src_path not in sys.path:
    sys.path.insert(0, src_path)

print(f"src path on sys.path: {src_path}")

In [ ]:
# Install dependencies if needed
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "flow_matching", "POT", "-q"])

In [4]:
import os, sys, time, json
import importlib
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
from functools import partial
from tqdm import trange

import Diffusion
import LossFunctions
import ConsistencyModels
import dist_utils
import Optimization
import experiment_utils
from ConsistencyModels import ConsistencyModeliCT
from LossFunctions import MMDLoss, RBF


for mod in [Diffusion, LossFunctions, ConsistencyModels,
            dist_utils, Optimization, experiment_utils]:
    importlib.reload(mod)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(PARAMS_DIR,     exist_ok=True)
print("Imports done.")

Imports done.

In [5]:
env_info = experiment_utils.get_environment_info()
experiment_utils.print_environment_info(env_info)

============================================================
ENVIRONMENT INFO
============================================================
  timestamp: 2026-04-26T04:41:09.802712
  torch_version: 2.10.0+cu128
  cuda_available: True
  cuda_version: 12.8
  device_name: NVIDIA L4
  packages:
    torch: 2.10.0+cu128
    numpy: 2.0.2
    flow_matching: 1.0.10
    POT: 0.9.6.post1
    matplotlib: 3.10.0
    pandas: 2.2.2
    tqdm: 4.67.3
============================================================

In [6]:
experiment_utils.set_global_seed(GLOBAL_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

[Seed] All random seeds set to 42
Using device: cuda

## GMM Parameters

In [7]:
# ============================================================
# GMM PARAMETERS
# Priority:
#   1. Load from PARAMS_DIR  (shared across runs, committed to repo)
#   2. Load from RESULTS_DIR (fallback from a previous run)
#   3. Generate fresh and save to both dirs
#
# To force regeneration: set FORCE_REGENERATE_PARAMS = True
# ============================================================
FORCE_REGENERATE_PARAMS = False

def _load_params():
    """Try PARAMS_DIR first, then RESULTS_DIR."""
    loaded = experiment_utils.load_gmm_params(PARAMS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from PARAMS_DIR: {PARAMS_DIR}")
        return loaded
    loaded = experiment_utils.load_gmm_params(RESULTS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from RESULTS_DIR: {RESULTS_DIR}")
        return loaded
    return None

loaded = None if FORCE_REGENERATE_PARAMS else _load_params()

if loaded is not None:
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = loaded
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()
else:
    print("[GMM] Generating fresh parameters...")
    experiment_utils.set_global_seed(GLOBAL_SEED)   # seed generation for reproducibility
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = \
        dist_utils.get_param_mog_with_target(
            dim_data=5, num_components=4, device='cpu',
            conditional_modes=2, distanceOrScale="Distance"
        )
    mog_means, mog_variances, weights = dist_utils.filter_and_normalize(
        mog_means, mog_variances, weights, threshold=0.001
    )
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()

    # save to PARAMS_DIR (canonical, share across runs)
    experiment_utils.save_gmm_params(
        mu_list, Sigma_list, alpha,
        mog_means, mog_variances, weights, x_star,
        PARAMS_DIR, EXPERIMENT_NAME
    )


print(f"x_star = {x_star}")
print(f"Number of conditional modes after filtering: {len(mog_means)}")

[GMM] Parameters loaded from /content/conditional-matching-paper/simulations/params/5D_cond_1D_gmm_params.pt
[GMM] Loaded from PARAMS_DIR: /content/conditional-matching-paper/simulations/params
x_star = tensor([-4.4615, -0.2913, -0.9775, -4.8282])
Number of conditional modes after filtering: 2

## Data

In [8]:
experiment_utils.set_global_seed(GLOBAL_SEED)
X = dist_utils.generate_mog_samples(25_000, mu_list, Sigma_list, alpha).float().to(device)

[Seed] All random seeds set to 42

## Train Models

### Consistency Model — P(Y|X=x)

In [9]:
experiment_utils.set_global_seed(GLOBAL_SEED)

B, C      = X.shape
nfeatures = C - CONDITION_ON
data_generator_cm = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha
)

Cos_ConsistencyModeliCT = ConsistencyModeliCT(
    nfeatures=nfeatures, condition_on=CONDITION_ON,
    nunits=NUNITS_CM, depth=NBLOCKS_CM
)

_loaded_cm = experiment_utils.load_checkpoint_with_hf_fallback(
    Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_cm:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    Cos_ConsistencyModeliCT.train_model(
        X=None, nepochs=NEPOCHS_CM, batch_size=BATCH_SIZE_CM,
        device=device, condition=CONDITION_ON,
        data_generator=data_generator_cm, use_improved_training=True
    )
    experiment_utils.save_model_checkpoint(
        Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] CM loaded from /content/conditional-matching-paper/simulations/checkpoints/5D_cond_1D/5D_cond_1D_CM_seed42.pt

### Diffusion — P(Y|X=x)

In [10]:
experiment_utils.set_global_seed(GLOBAL_SEED)

X_train   = dist_utils.generate_mog_samples(1_000, mu_list, Sigma_list, alpha).float().to(device)
nfeatures = X_train.shape[1]

data_generator_diff_cond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha, kernel_func=None
)

model_cond = Diffusion.DiffusionModel(
    nfeatures=nfeatures, nblocks=NBLOCKS, nunits=NUNITS,
    condition=True, condition_on=CONDITION_ON,
    diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_cond = experiment_utils.load_checkpoint_with_hf_fallback(
    model_cond, "Diffusion_cond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_cond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_cond.train_model(
        None, data_generator=data_generator_diff_cond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_cond, "Diffusion_cond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_cond loaded from /content/conditional-matching-paper/simulations/checkpoints/5D_cond_1D/5D_cond_1D_Diffusion_cond_seed42.pt

### Diffusion — P(X=x)

In [11]:
experiment_utils.set_global_seed(GLOBAL_SEED)

data_generator_diff_uncond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha,
    kernel_func=lambda X: X[:, :CONDITION_ON]
)

model_uncond = Diffusion.DiffusionModel(
    nfeatures=CONDITION_ON, nblocks=NBLOCKS, nunits=NUNITS,
    condition=False, diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_uncond = experiment_utils.load_checkpoint_with_hf_fallback(
    model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_uncond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_uncond.train_model(
        None, data_generator=data_generator_diff_uncond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_uncond loaded from /content/conditional-matching-paper/simulations/checkpoints/5D_cond_1D/5D_cond_1D_Diffusion_uncond_seed42.pt

### SANITY CHECK: Compare CM vs Diffusion conditional quality

In [13]:
RUN_SANITY_CHECK = True
SANITY_K = 500

if RUN_SANITY_CHECK:
    mmd_loss = MMDLoss(kernel=RBF())
    N_SANITY_SAMPLES = 500

    mmd_diff_list = []
    mmd_cm_list   = []

    for k in trange(SANITY_K, desc="Sanity check"):
        experiment_utils.set_run_seed(GLOBAL_SEED, k)

        # Sample x from the analytic joint distribution, take only the x part
        joint_sample = dist_utils.generate_mog_samples_not_differentiable(
            1, mu_list, Sigma_list, alpha
        ).float()  # shape (1, CONDITION_ON + n_y)
        x_sample = joint_sample[:, :CONDITION_ON]          # shape (1, CONDITION_ON)
        x_vec    = x_sample.view(-1).cpu()                 # shape (CONDITION_ON,)

        # Analytic conditional samples
        mu_cond, Sigma_cond = dist_utils.compute_conditionals(mu_list, Sigma_list, x_vec)
        w_cond = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_vec)
        analytic_samples = dist_utils.generate_mog_samples_not_differentiable(
            N_SANITY_SAMPLES, mu_cond, Sigma_cond, w_cond
        ).float().to(device)

        # Diffusion conditional samples
        cond_rep = x_sample.to(device).repeat(N_SANITY_SAMPLES, 1)
        diff_samples, _, _ = model_cond.sample(
            nsamples=N_SANITY_SAMPLES, condition_x=cond_rep, device=device
        )
        diff_samples = diff_samples[:, CONDITION_ON:]  # keep only y part
        # CM conditional samples
        cm_samples, _, _ = Cos_ConsistencyModeliCT.sample(
            nsamples=N_SANITY_SAMPLES, condition_x=cond_rep, device=device
        )
        # CM already outputs y only (nfeatures = dim_y)

        mmd_diff = mmd_loss(diff_samples, analytic_samples).item()
        mmd_cm   = mmd_loss(cm_samples,   analytic_samples).item()

        mmd_diff_list.append(mmd_diff)
        mmd_cm_list.append(mmd_cm)

    print(f"\n--- Sanity Check Summary (K={SANITY_K}) ---")
    print(f"Diffusion  MMD: mean={np.mean(mmd_diff_list):.5f}  std={np.std(mmd_diff_list):.5f}")
    print(f"CM         MMD: mean={np.mean(mmd_cm_list):.5f}  std={np.std(mmd_cm_list):.5f}")
else:
    print("[Sanity check skipped] Set RUN_SANITY_CHECK = True to run.")

Sanity check: 100%|██████████| 500/500 [02:50<00:00,  2.93it/s]

--- Sanity Check Summary (K=500) ---
Diffusion  MMD: mean=0.01025  std=0.01413
CM         MMD: mean=0.18181  std=0.29904

## Optimize

### MLGD

In [ ]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_list = []
l2_gmm_LGD_list   = []
l2_x_LGD_list     = []
lgd_times         = []
final_loss_LGD    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, model_cond, mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        num_x_t=NUM_X_T_LGD
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_times.append(end_time - start_time)
    final_loss_LGD.append(final_loss)
    best_x_t_LGD_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_list.append(l2_gmm)
    l2_x_LGD_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  0%|          | 0/25 [00:00<?, ?it/s]/content/conditional-matching-paper/simulations/src/dist_utils.py:466: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  exponent = -0.5 * diff.T @ Sigma_22_inv @ diff
  4%|▍         | 1/25 [05:30<2:12:15, 330.66s/it]

[1] seed=42 | L2 GMM: 0.529432 | L2 to x*: 34.612186

  8%|▊         | 2/25 [11:00<2:06:31, 330.07s/it]

[2] seed=43 | L2 GMM: 0.548365 | L2 to x*: 34.664753

 12%|█▏        | 3/25 [16:30<2:01:04, 330.22s/it]

[3] seed=44 | L2 GMM: 0.158224 | L2 to x*: 24.957411

 16%|█▌        | 4/25 [22:00<1:55:27, 329.88s/it]

[4] seed=45 | L2 GMM: 0.614047 | L2 to x*: 117.063362

 20%|██        | 5/25 [27:28<1:49:48, 329.41s/it]

[5] seed=46 | L2 GMM: 0.691624 | L2 to x*: 117.693718

 24%|██▍       | 6/25 [32:57<1:44:16, 329.28s/it]

[6] seed=47 | L2 GMM: 0.481901 | L2 to x*: 34.145203

 28%|██▊       | 7/25 [38:26<1:38:43, 329.11s/it]

[7] seed=48 | L2 GMM: 0.691624 | L2 to x*: 291.947449

 32%|███▏      | 8/25 [43:58<1:33:29, 329.98s/it]

[8] seed=49 | L2 GMM: 0.158292 | L2 to x*: 18.294586

 36%|███▌      | 9/25 [49:32<1:28:20, 331.28s/it]

[9] seed=50 | L2 GMM: 0.157335 | L2 to x*: 20.616278

 40%|████      | 10/25 [55:02<1:22:45, 331.03s/it]

[10] seed=51 | L2 GMM: 0.156961 | L2 to x*: 21.135889

 44%|████▍     | 11/25 [1:00:32<1:17:06, 330.49s/it]

[11] seed=52 | L2 GMM: 1.217805 | L2 to x*: 22.066074

 48%|████▊     | 12/25 [1:06:02<1:11:34, 330.38s/it]

[12] seed=53 | L2 GMM: 0.157485 | L2 to x*: 24.205198

 52%|█████▏    | 13/25 [1:11:31<1:06:01, 330.12s/it]

[13] seed=54 | L2 GMM: 0.449814 | L2 to x*: 33.206360

 56%|█████▌    | 14/25 [1:17:03<1:00:35, 330.51s/it]

[14] seed=55 | L2 GMM: 0.159622 | L2 to x*: 26.014168

 60%|██████    | 15/25 [1:22:33<55:04, 330.45s/it]

[15] seed=56 | L2 GMM: 0.157091 | L2 to x*: 22.595278

 64%|██████▍   | 16/25 [1:28:05<49:36, 330.76s/it]

[16] seed=57 | L2 GMM: 0.156763 | L2 to x*: 21.687803

 68%|██████▊   | 17/25 [1:33:35<44:05, 330.74s/it]

[17] seed=58 | L2 GMM: 0.157533 | L2 to x*: 18.795338

 72%|███████▏  | 18/25 [1:39:06<38:34, 330.66s/it]

[18] seed=59 | L2 GMM: 0.499073 | L2 to x*: 34.566738

 76%|███████▌  | 19/25 [1:44:36<33:03, 330.65s/it]

[19] seed=60 | L2 GMM: 0.691624 | L2 to x*: 456.556793

 80%|████████  | 20/25 [1:50:08<27:34, 330.89s/it]

[20] seed=61 | L2 GMM: 0.691624 | L2 to x*: 936.436646

 84%|████████▍ | 21/25 [1:55:40<22:04, 331.19s/it]

[21] seed=62 | L2 GMM: 0.160135 | L2 to x*: 24.982916

 88%|████████▊ | 22/25 [2:01:11<16:33, 331.22s/it]

[22] seed=63 | L2 GMM: 0.158321 | L2 to x*: 26.397943

 92%|█████████▏| 23/25 [2:06:42<11:02, 331.11s/it]

[23] seed=64 | L2 GMM: 0.157803 | L2 to x*: 26.481178

 96%|█████████▌| 24/25 [2:12:13<05:31, 331.11s/it]

[24] seed=65 | L2 GMM: 0.548032 | L2 to x*: 34.137093

100%|██████████| 25/25 [2:17:44<00:00, 330.59s/it]

[25] seed=66 | L2 GMM: 0.691624 | L2 to x*: 1231.145386

### MLGD-F

In [ ]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_CM_list = []
l2_gmm_LGD_CM_list   = []
l2_x_LGD_CM_list     = []
lgd_cm_times         = []
final_loss_LGD_CM    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, Cos_ConsistencyModeliCT,
        mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        CM=True, FLAG=False, num_x_t=NUM_X_T_LGD_CM
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_cm_times.append(end_time - start_time)
    final_loss_LGD_CM.append(final_loss)
    best_x_t_LGD_CM_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_CM_list.append(l2_gmm)
    l2_x_LGD_CM_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [00:23<09:16, 23.17s/it]

[1] seed=42 | L2 GMM: 0.156503 | L2 to x*: 20.987396

  8%|▊         | 2/25 [00:46<08:51, 23.11s/it]

[2] seed=43 | L2 GMM: 1.161666 | L2 to x*: 14.060696

 12%|█▏        | 3/25 [01:09<08:28, 23.13s/it]

[3] seed=44 | L2 GMM: 1.162296 | L2 to x*: 11.509062

 16%|█▌        | 4/25 [01:32<08:05, 23.13s/it]

[4] seed=45 | L2 GMM: 0.156784 | L2 to x*: 29.096563

 20%|██        | 5/25 [01:55<07:41, 23.08s/it]

[5] seed=46 | L2 GMM: 1.217805 | L2 to x*: 48.323860

 24%|██▍       | 6/25 [02:18<07:17, 23.03s/it]

[6] seed=47 | L2 GMM: 0.156730 | L2 to x*: 20.421059

 28%|██▊       | 7/25 [02:41<06:53, 22.99s/it]

[7] seed=48 | L2 GMM: 0.158784 | L2 to x*: 26.809963

 32%|███▏      | 8/25 [03:04<06:30, 22.98s/it]

[8] seed=49 | L2 GMM: 0.156492 | L2 to x*: 18.452351

 36%|███▌      | 9/25 [03:27<06:07, 22.99s/it]

[9] seed=50 | L2 GMM: 0.606719 | L2 to x*: 55.588234

 40%|████      | 10/25 [03:50<05:44, 22.99s/it]

[10] seed=51 | L2 GMM: 1.212552 | L2 to x*: 21.287460

 44%|████▍     | 11/25 [04:13<05:21, 22.96s/it]

[11] seed=52 | L2 GMM: 1.217805 | L2 to x*: 44.607677

 48%|████▊     | 12/25 [04:36<04:58, 22.99s/it]

[12] seed=53 | L2 GMM: 0.156544 | L2 to x*: 20.946852

 52%|█████▏    | 13/25 [04:59<04:36, 23.00s/it]

[13] seed=54 | L2 GMM: 0.158052 | L2 to x*: 23.249220

 56%|█████▌    | 14/25 [05:22<04:13, 23.04s/it]

[14] seed=55 | L2 GMM: 0.156489 | L2 to x*: 21.078539

 60%|██████    | 15/25 [05:45<03:49, 22.98s/it]

[15] seed=56 | L2 GMM: 0.159902 | L2 to x*: 14.840860

 64%|██████▍   | 16/25 [06:08<03:27, 23.04s/it]

[16] seed=57 | L2 GMM: 1.217805 | L2 to x*: 26.938686

 68%|██████▊   | 17/25 [06:31<03:03, 22.99s/it]

[17] seed=58 | L2 GMM: 0.160295 | L2 to x*: 39.173843

 72%|███████▏  | 18/25 [06:54<02:40, 22.99s/it]

[18] seed=59 | L2 GMM: 0.161039 | L2 to x*: 22.100428

 76%|███████▌  | 19/25 [07:17<02:18, 23.03s/it]

[19] seed=60 | L2 GMM: 0.156624 | L2 to x*: 25.516842

 80%|████████  | 20/25 [07:40<01:54, 22.98s/it]

[20] seed=61 | L2 GMM: 0.157189 | L2 to x*: 29.902603

 84%|████████▍ | 21/25 [08:03<01:32, 23.03s/it]

[21] seed=62 | L2 GMM: 0.156544 | L2 to x*: 25.063259

 88%|████████▊ | 22/25 [08:26<01:08, 22.99s/it]

[22] seed=63 | L2 GMM: 0.164404 | L2 to x*: 16.969168

 92%|█████████▏| 23/25 [08:49<00:45, 22.91s/it]

[23] seed=64 | L2 GMM: 0.156793 | L2 to x*: 18.785101

 96%|█████████▌| 24/25 [09:11<00:22, 22.85s/it]

[24] seed=65 | L2 GMM: 0.159442 | L2 to x*: 29.321991

100%|██████████| 25/25 [09:34<00:00, 22.99s/it]

[25] seed=66 | L2 GMM: 0.159510 | L2 to x*: 37.402809

## Results

In [ ]:
rows = [
    experiment_utils.summary_row("MLGD",    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.summary_row("MLGD-F", l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df = pd.DataFrame(rows).set_index("Method")
display(df)

rows_top10 = [
    experiment_utils.top10_stats("MLGD",    final_loss_LGD,    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.top10_stats("MLGD-F", final_loss_LGD_CM, l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df_top10 = pd.DataFrame(rows_top10).set_index("Method")
display(df_top10)

,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s)
Method,,,,,,
LGD,0.4097,0.2771,146.1762,296.2190,330.57,1.18
LGD-CM,0.4258,0.4430,26.4974,10.7230,22.98,0.13

,Loss mean,Loss std,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s),Top-k selected
Method,,,,,,,,,
LGD,0.2668,0.0698,0.3688,0.1745,29.9101,5.7060,330.46,0.82,10
LGD-CM,0.2624,0.0681,0.4649,0.4687,23.3615,7.1113,23.01,0.13,10

In [ ]:
def to_python(val):
    if isinstance(val, torch.Tensor):
        return val.detach().cpu().tolist()
    if isinstance(val, np.ndarray):
        return val.tolist()
    if hasattr(val, "item"):
        return val.item()
    return val

results = {
    "experiment":  EXPERIMENT_NAME,
    "seed":        GLOBAL_SEED,
    "environment": env_info,
    "MLGD": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_list],
        "final_loss": [to_python(l) for l in final_loss_LGD],
        "l2_gmm":     l2_gmm_LGD_list,
        "l2_x":       l2_x_LGD_list,
        "times":      lgd_times,
    },
    "MLGD-F": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_CM_list],
        "final_loss": [to_python(l) for l in final_loss_LGD_CM],
        "l2_gmm":     l2_gmm_LGD_CM_list,
        "l2_x":       l2_x_LGD_CM_list,
        "times":      lgd_cm_times,
    },
    "meta": {
        "n_attemp_optim":            N_ATTEMP_OPTIM,
        "nsamples_in_optim_for_mmd": NSAMPLES_IN_OPTIM_FOR_MMD,
        "x_star":                    to_python(x_star),
    },
}

path = os.path.join(RESULTS_DIR, f"{EXPERIMENT_NAME}_results_seed{GLOBAL_SEED}.json")
with open(path, "w") as f:
    json.dump(results, f, indent=2)
print(f"Results saved to {path}")

Results saved to /content/conditional-matching-paper/simulations/results/5D_cond_1D/5D_cond_1D_results_seed42.json