# Experiment: 10D cond 1D

dim(x)=9, dim(y)=1 — comparing LGD vs LGD-CM.

In [1]:
import os
# ============================================================
# CONFIG — only this cell changes between notebooks
# ============================================================
EXPERIMENT_NAME   = "10D_cond_1D"
GLOBAL_SEED       = 42
FORCE_RETRAIN     = False

BASE_DIR = os.path.normpath(os.path.join(os.getcwd(), ".."))
PARAMS_DIR        = f"{BASE_DIR}/params"
CHECKPOINT_DIR    = f"{BASE_DIR}/checkpoints/{EXPERIMENT_NAME}"
RESULTS_DIR       = f"{BASE_DIR}/results/{EXPERIMENT_NAME}"

# Architecture — Diffusion models
NBLOCKS           = 8
NUNITS            = 512

# Architecture — Consistency Model
NBLOCKS_CM        = 8
NUNITS_CM         = 512

# Training — Diffusion
NEPOCHS           = 40_000
BATCH_SIZE        = 4_096

# Training — Consistency Model
NEPOCHS_CM        = 40_000
BATCH_SIZE_CM     = 4_096

# Diffusion
DIFFUSION_STEPS   = 100

# Optimization
N_ATTEMP_OPTIM              = 25
NSAMPLES_IN_OPTIM_FOR_MMD   = 250
NUM_X_T_LGD                 = 5
NUM_X_T_LGD_CM              = 5

# GMM dimensions
CONDITION_ON      = 9   # dim(x)=9, dim(y)=1

In [ ]:
import os, sys

# ── point Python at simulations/src where all .py modules live ──
src_path = os.path.join(os.path.dirname(os.path.abspath("__file__")), "..", "src")
src_path = os.path.normpath(src_path)
if src_path not in sys.path:
    sys.path.insert(0, src_path)

print(f"src path on sys.path: {src_path}")

In [ ]:
# Install dependencies if needed
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "flow_matching", "POT", "-q"])

In [4]:
import os, sys, time, json
import importlib
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
from functools import partial
from tqdm import trange

import Diffusion
import LossFunctions
import ConsistencyModels
import dist_utils
import Optimization
import experiment_utils
from ConsistencyModels import ConsistencyModeliCT
from LossFunctions import MMDLoss, RBF

for mod in [Diffusion, LossFunctions, ConsistencyModels,
            dist_utils, Optimization, experiment_utils]:
    importlib.reload(mod)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(PARAMS_DIR,     exist_ok=True)
print("Imports done.")

Imports done.

In [5]:
env_info = experiment_utils.get_environment_info()
experiment_utils.print_environment_info(env_info)

============================================================
ENVIRONMENT INFO
============================================================
  timestamp: 2026-04-26T04:50:22.349418
  torch_version: 2.10.0+cu128
  cuda_available: True
  cuda_version: 12.8
  device_name: NVIDIA L4
  packages:
    torch: 2.10.0+cu128
    numpy: 2.0.2
    flow_matching: 1.0.10
    POT: 0.9.6.post1
    matplotlib: 3.10.0
    pandas: 2.2.2
    tqdm: 4.67.3
============================================================

In [6]:
experiment_utils.set_global_seed(GLOBAL_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

[Seed] All random seeds set to 42
Using device: cuda

## GMM Parameters

In [7]:
# ============================================================
# GMM PARAMETERS
# Priority:
#   1. Load from PARAMS_DIR  (shared across runs, committed to repo)
#   2. Load from RESULTS_DIR (fallback from a previous run)
#   3. Generate fresh and save to both dirs
#
# To force regeneration: set FORCE_REGENERATE_PARAMS = True
# ============================================================
FORCE_REGENERATE_PARAMS = False

def _load_params():
    """Try PARAMS_DIR first, then RESULTS_DIR."""
    loaded = experiment_utils.load_gmm_params(PARAMS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from PARAMS_DIR: {PARAMS_DIR}")
        return loaded
    loaded = experiment_utils.load_gmm_params(RESULTS_DIR, EXPERIMENT_NAME)
    if loaded is not None:
        print(f"[GMM] Loaded from RESULTS_DIR: {RESULTS_DIR}")
        return loaded
    return None

loaded = None if FORCE_REGENERATE_PARAMS else _load_params()

if loaded is not None:
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = loaded
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()
else:
    print("[GMM] Generating fresh parameters...")
    experiment_utils.set_global_seed(GLOBAL_SEED)   # seed generation for reproducibility
    mu_list, Sigma_list, alpha, mog_means, mog_variances, weights, x_star = \
        dist_utils.get_param_mog_with_target(
            dim_data=10, num_components=4, device='cpu',
            conditional_modes=2, distanceOrScale="Distance"
        )
    mog_means, mog_variances, weights = dist_utils.filter_and_normalize(
        mog_means, mog_variances, weights, threshold=0.001
    )
    mu_list    = [mu.float() for mu in mu_list]
    Sigma_list = [cov.float() for cov in Sigma_list]
    alpha      = alpha.float()

    # save to PARAMS_DIR (canonical, share across runs)
    experiment_utils.save_gmm_params(
        mu_list, Sigma_list, alpha,
        mog_means, mog_variances, weights, x_star,
        PARAMS_DIR, EXPERIMENT_NAME
    )


print(f"x_star = {x_star}")
print(f"Number of conditional modes after filtering: {len(mog_means)}")

[GMM] Parameters loaded from /content/conditional-matching-paper/simulations/params/10D_cond_1D_gmm_params.pt
[GMM] Loaded from PARAMS_DIR: /content/conditional-matching-paper/simulations/params
x_star = tensor([ -4.5404,   2.7114,   0.5513, -11.2950,   3.0335,  -0.6915,   4.1551,
         -1.2385,  -4.0147])
Number of conditional modes after filtering: 2

## Data

In [8]:
experiment_utils.set_global_seed(GLOBAL_SEED)
X = dist_utils.generate_mog_samples(25_000, mu_list, Sigma_list, alpha).float().to(device)

[Seed] All random seeds set to 42

## Train Models

### Consistency Model — P(Y|X=x)

In [9]:
experiment_utils.set_global_seed(GLOBAL_SEED)

B, C      = X.shape
nfeatures = C - CONDITION_ON
data_generator_cm = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha
)

Cos_ConsistencyModeliCT = ConsistencyModeliCT(
    nfeatures=nfeatures, condition_on=CONDITION_ON,
    nunits=NUNITS_CM, depth=NBLOCKS_CM
)

_loaded_cm = experiment_utils.load_checkpoint_with_hf_fallback(
    Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_cm:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    Cos_ConsistencyModeliCT.train_model(
        X=None, nepochs=NEPOCHS_CM, batch_size=BATCH_SIZE_CM,
        device=device, condition=CONDITION_ON,
        data_generator=data_generator_cm, use_improved_training=True
    )
    experiment_utils.save_model_checkpoint(
        Cos_ConsistencyModeliCT, "CM", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] CM loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_CM_seed42.pt

### Diffusion — P(Y|X=x)

In [10]:
experiment_utils.set_global_seed(GLOBAL_SEED)

X_train   = dist_utils.generate_mog_samples(1_000, mu_list, Sigma_list, alpha).float().to(device)
nfeatures = X_train.shape[1]

data_generator_diff_cond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha, kernel_func=None
)

model_cond = Diffusion.DiffusionModel(
    nfeatures=nfeatures, nblocks=NBLOCKS, nunits=NUNITS,
    condition=True, condition_on=CONDITION_ON,
    diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_cond = experiment_utils.load_checkpoint_with_hf_fallback(
    model_cond, "Diffusion_cond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_cond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_cond.train_model(
        None, data_generator=data_generator_diff_cond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_cond, "Diffusion_cond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_cond loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_cond_seed42.pt

### Diffusion — P(X=x)

In [11]:
experiment_utils.set_global_seed(GLOBAL_SEED)

data_generator_diff_uncond = partial(
    dist_utils.generate_mog_samples_not_differentiable,
    means=mu_list, variances=Sigma_list, weights=alpha,
    kernel_func=lambda X: X[:, :CONDITION_ON]
)

model_uncond = Diffusion.DiffusionModel(
    nfeatures=CONDITION_ON, nblocks=NBLOCKS, nunits=NUNITS,
    condition=False, diffusion_steps=DIFFUSION_STEPS
)

_loaded_diff_uncond = experiment_utils.load_checkpoint_with_hf_fallback(
    model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
    EXPERIMENT_NAME, GLOBAL_SEED, device
) if not FORCE_RETRAIN else False

if not _loaded_diff_uncond:
    experiment_utils.set_global_seed(GLOBAL_SEED)
    model_uncond.train_model(
        None, data_generator=data_generator_diff_uncond,
        nepochs=NEPOCHS, batch_size=BATCH_SIZE,
        condition_on=CONDITION_ON
    )
    experiment_utils.save_model_checkpoint(
        model_uncond, "Diffusion_uncond", CHECKPOINT_DIR,
        EXPERIMENT_NAME, GLOBAL_SEED
    )

[Seed] All random seeds set to 42
[Checkpoint] Diffusion_uncond loaded from /content/conditional-matching-paper/simulations/checkpoints/10D_cond_1D/10D_cond_1D_Diffusion_uncond_seed42.pt

### SANITY CHECK: Compare CM vs Diffusion conditional quality

In [12]:

RUN_SANITY_CHECK = True
SANITY_K = 500

if RUN_SANITY_CHECK:
    mmd_loss = MMDLoss(kernel=RBF())
    N_SANITY_SAMPLES = 500

    mmd_diff_list = []
    mmd_cm_list   = []

    for k in trange(SANITY_K, desc="Sanity check"):
        experiment_utils.set_run_seed(GLOBAL_SEED, k)

        # Sample x from the analytic joint distribution, take only the x part
        joint_sample = dist_utils.generate_mog_samples_not_differentiable(
            1, mu_list, Sigma_list, alpha
        ).float()  # shape (1, CONDITION_ON + n_y)
        x_sample = joint_sample[:, :CONDITION_ON]          # shape (1, CONDITION_ON)
        x_vec    = x_sample.view(-1).cpu()                 # shape (CONDITION_ON,)

        # Analytic conditional samples
        mu_cond, Sigma_cond = dist_utils.compute_conditionals(mu_list, Sigma_list, x_vec)
        w_cond = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_vec)
        analytic_samples = dist_utils.generate_mog_samples_not_differentiable(
            N_SANITY_SAMPLES, mu_cond, Sigma_cond, w_cond
        ).float().to(device)

        # Diffusion conditional samples
        cond_rep = x_sample.to(device).repeat(N_SANITY_SAMPLES, 1)
        diff_samples, _, _ = model_cond.sample(
            nsamples=N_SANITY_SAMPLES, condition_x=cond_rep, device=device
        )
        diff_samples = diff_samples[:, CONDITION_ON:]  # keep only y part

        # CM conditional samples
        cm_samples, _, _ = Cos_ConsistencyModeliCT.sample(
            nsamples=N_SANITY_SAMPLES, condition_x=cond_rep, device=device
        )
        # CM already outputs y only (nfeatures = dim_y)

        mmd_diff = mmd_loss(diff_samples, analytic_samples).item()
        mmd_cm   = mmd_loss(cm_samples,   analytic_samples).item()

        mmd_diff_list.append(mmd_diff)
        mmd_cm_list.append(mmd_cm)

    print(f"\n--- Sanity Check Summary (K={SANITY_K}) ---")
    print(f"Diffusion  MMD: mean={np.mean(mmd_diff_list):.5f}  std={np.std(mmd_diff_list):.5f}")
    print(f"CM         MMD: mean={np.mean(mmd_cm_list):.5f}  std={np.std(mmd_cm_list):.5f}")
else:
    print("[Sanity check skipped] Set RUN_SANITY_CHECK = True to run.")

Sanity check:   0%|          | 0/500 [00:00<?, ?it/s]/content/conditional-matching-paper/simulations/src/dist_utils.py:466: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  exponent = -0.5 * diff.T @ Sigma_22_inv @ diff
Sanity check: 100%|██████████| 500/500 [03:26<00:00,  2.42it/s]

--- Sanity Check Summary (K=500) ---
Diffusion  MMD: mean=0.02278  std=0.05931
CM         MMD: mean=0.14498  std=0.19678

## Optimize

### MLGD

In [ ]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_list = []
l2_gmm_LGD_list   = []
l2_x_LGD_list     = []
lgd_times         = []
final_loss_LGD    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, model_cond, mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        num_x_t=NUM_X_T_LGD
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_times.append(end_time - start_time)
    final_loss_LGD.append(final_loss)
    best_x_t_LGD_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_list.append(l2_gmm)
    l2_x_LGD_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [06:59<2:47:51, 419.66s/it]

[1] seed=42 | L2 GMM: 0.870136 | L2 to x*: 11.335978

  8%|▊         | 2/25 [13:58<2:40:44, 419.35s/it]

[2] seed=43 | L2 GMM: 0.872331 | L2 to x*: 8.415682

 12%|█▏        | 3/25 [20:58<2:33:53, 419.69s/it]

[3] seed=44 | L2 GMM: 0.504017 | L2 to x*: 4.696059

 16%|█▌        | 4/25 [27:59<2:26:59, 419.99s/it]

[4] seed=45 | L2 GMM: 0.870246 | L2 to x*: 13.100332

 20%|██        | 5/25 [34:58<2:19:57, 419.86s/it]

[5] seed=46 | L2 GMM: 0.953854 | L2 to x*: 7.203979

 24%|██▍       | 6/25 [42:00<2:13:09, 420.52s/it]

[6] seed=47 | L2 GMM: 0.723163 | L2 to x*: 29.935089

 28%|██▊       | 7/25 [48:59<2:06:00, 420.01s/it]

[7] seed=48 | L2 GMM: 0.325700 | L2 to x*: 12.255443

 32%|███▏      | 8/25 [55:58<1:58:54, 419.66s/it]

[8] seed=49 | L2 GMM: 0.716619 | L2 to x*: 6.565616

 36%|███▌      | 9/25 [1:02:59<1:52:02, 420.15s/it]

[9] seed=50 | L2 GMM: 0.503935 | L2 to x*: 5.378629

 40%|████      | 10/25 [1:10:01<1:45:10, 420.70s/it]

[10] seed=51 | L2 GMM: 0.775703 | L2 to x*: 19.578939

 44%|████▍     | 11/25 [1:17:02<1:38:07, 420.55s/it]

[11] seed=52 | L2 GMM: 0.498002 | L2 to x*: 18.801722

 48%|████▊     | 12/25 [1:24:02<1:31:06, 420.50s/it]

[12] seed=53 | L2 GMM: 0.953854 | L2 to x*: 51.944309

 52%|█████▏    | 13/25 [1:31:02<1:24:03, 420.26s/it]

[13] seed=54 | L2 GMM: 0.500614 | L2 to x*: 12.879984

 56%|█████▌    | 14/25 [1:38:02<1:17:01, 420.17s/it]

[14] seed=55 | L2 GMM: 0.194603 | L2 to x*: 5.652868

 60%|██████    | 15/25 [1:45:04<1:10:09, 420.95s/it]

[15] seed=56 | L2 GMM: 0.773921 | L2 to x*: 5.353535

 64%|██████▍   | 16/25 [1:52:11<1:03:24, 422.73s/it]

[16] seed=57 | L2 GMM: 0.135397 | L2 to x*: 4.795977

 68%|██████▊   | 17/25 [1:59:12<56:18, 422.28s/it]

[17] seed=58 | L2 GMM: 0.953334 | L2 to x*: 8.600769

 72%|███████▏  | 18/25 [2:06:15<49:15, 422.25s/it]

[18] seed=59 | L2 GMM: 0.488863 | L2 to x*: 6.104619

 76%|███████▌  | 19/25 [2:13:17<42:14, 422.36s/it]

[19] seed=60 | L2 GMM: 0.164807 | L2 to x*: 8.389001

 80%|████████  | 20/25 [2:20:21<35:14, 422.85s/it]

[20] seed=61 | L2 GMM: 0.811294 | L2 to x*: 17.792246

 84%|████████▍ | 21/25 [2:27:23<28:09, 422.44s/it]

[21] seed=62 | L2 GMM: 0.723164 | L2 to x*: 14.158860

 88%|████████▊ | 22/25 [2:34:26<21:07, 422.60s/it]

[22] seed=63 | L2 GMM: 0.504536 | L2 to x*: 7.475062

 92%|█████████▏| 23/25 [2:41:32<14:07, 423.79s/it]

[23] seed=64 | L2 GMM: 0.127999 | L2 to x*: 41.992699

 96%|█████████▌| 24/25 [2:48:36<07:03, 423.69s/it]

[24] seed=65 | L2 GMM: 0.502901 | L2 to x*: 16.294025

100%|██████████| 25/25 [2:55:41<00:00, 421.64s/it]

[25] seed=66 | L2 GMM: 0.504536 | L2 to x*: 17.104406

### MLGD-F

In [ ]:
# NOTE: optimize_LGD call is untouched — only seed management added around it
best_x_t_LGD_CM_list = []
l2_gmm_LGD_CM_list   = []
l2_x_LGD_CM_list     = []
lgd_cm_times         = []
final_loss_LGD_CM    = []

for i in trange(N_ATTEMP_OPTIM):
    run_seed = experiment_utils.set_run_seed(GLOBAL_SEED, i)

    start_time = time.time()
    best_x_t, best_x_0_cont_xt_hat, final_loss = Optimization.optimize_LGD(
        model_uncond, Cos_ConsistencyModeliCT,
        mog_means, mog_variances, weights,
        mu_list, Sigma_list, alpha,
        nsamples=NSAMPLES_IN_OPTIM_FOR_MMD, loss="MMD", device=device,
        CM=True, FLAG=False, num_x_t=NUM_X_T_LGD_CM
    )
    best_x_t = best_x_t.reshape(-1, 1)
    end_time = time.time()

    lgd_cm_times.append(end_time - start_time)
    final_loss_LGD_CM.append(final_loss)
    best_x_t_LGD_CM_list.append(best_x_t)

    x_pred_t = best_x_t.float().view(-1).cpu()
    mu_pred, Sigma_pred = dist_utils.compute_conditionals(mu_list, Sigma_list, x_pred_t)
    w_pred = dist_utils.compute_alpha(mu_list, Sigma_list, alpha, x_pred_t)

    l2_gmm = dist_utils.gmm_l2_distance(
        mu_pred, Sigma_pred, w_pred, mog_means, mog_variances, weights
    )
    l2_x = (x_pred_t - x_star.float().cpu()).pow(2).sum().sqrt().item()

    l2_gmm_LGD_CM_list.append(l2_gmm)
    l2_x_LGD_CM_list.append(l2_x)
    print(f"[{i+1}] seed={run_seed} | L2 GMM: {l2_gmm:.6f} | L2 to x*: {l2_x:.6f}")

  4%|▍         | 1/25 [00:28<11:31, 28.80s/it]

[1] seed=42 | L2 GMM: 0.034033 | L2 to x*: 2.575763

  8%|▊         | 2/25 [00:57<10:57, 28.57s/it]

[2] seed=43 | L2 GMM: 0.735723 | L2 to x*: 10.491535

 12%|█▏        | 3/25 [01:25<10:25, 28.44s/it]

[3] seed=44 | L2 GMM: 0.504536 | L2 to x*: 14.738869

 16%|█▌        | 4/25 [01:53<09:55, 28.36s/it]

[4] seed=45 | L2 GMM: 0.504536 | L2 to x*: 11.440372

 20%|██        | 5/25 [02:22<09:28, 28.41s/it]

[5] seed=46 | L2 GMM: 0.807887 | L2 to x*: 15.144411

 24%|██▍       | 6/25 [02:50<09:01, 28.51s/it]

[6] seed=47 | L2 GMM: 0.611726 | L2 to x*: 16.660404

 28%|██▊       | 7/25 [03:19<08:31, 28.43s/it]

[7] seed=48 | L2 GMM: 0.504536 | L2 to x*: 11.370663

 32%|███▏      | 8/25 [03:47<08:03, 28.43s/it]

[8] seed=49 | L2 GMM: 0.504534 | L2 to x*: 8.677122

 36%|███▌      | 9/25 [04:15<07:34, 28.40s/it]

[9] seed=50 | L2 GMM: 0.211179 | L2 to x*: 3.925891

 40%|████      | 10/25 [04:44<07:07, 28.50s/it]

[10] seed=51 | L2 GMM: 0.046601 | L2 to x*: 2.036883

 44%|████▍     | 11/25 [05:13<06:40, 28.60s/it]

[11] seed=52 | L2 GMM: 0.232829 | L2 to x*: 6.244724

 48%|████▊     | 12/25 [05:42<06:11, 28.61s/it]

[12] seed=53 | L2 GMM: 0.130488 | L2 to x*: 39.598972

 52%|█████▏    | 13/25 [06:10<05:42, 28.57s/it]

[13] seed=54 | L2 GMM: 0.504536 | L2 to x*: 15.536956

 56%|█████▌    | 14/25 [06:39<05:13, 28.52s/it]

[14] seed=55 | L2 GMM: 0.120960 | L2 to x*: 47.186485

 60%|██████    | 15/25 [07:07<04:46, 28.62s/it]

[15] seed=56 | L2 GMM: 0.149576 | L2 to x*: 31.941689

 64%|██████▍   | 16/25 [07:36<04:17, 28.56s/it]

[16] seed=57 | L2 GMM: 0.953854 | L2 to x*: 14.704363

 68%|██████▊   | 17/25 [08:05<03:49, 28.68s/it]

[17] seed=58 | L2 GMM: 0.109406 | L2 to x*: 2.332400

 72%|███████▏  | 18/25 [08:33<03:20, 28.59s/it]

[18] seed=59 | L2 GMM: 0.953851 | L2 to x*: 9.708304

 76%|███████▌  | 19/25 [09:02<02:52, 28.71s/it]

[19] seed=60 | L2 GMM: 0.317411 | L2 to x*: 2.376134

 80%|████████  | 20/25 [09:31<02:23, 28.73s/it]

[20] seed=61 | L2 GMM: 0.382949 | L2 to x*: 4.249338

 84%|████████▍ | 21/25 [10:00<01:55, 28.81s/it]

[21] seed=62 | L2 GMM: 0.395470 | L2 to x*: 2.460353

 88%|████████▊ | 22/25 [10:29<01:26, 28.84s/it]

[22] seed=63 | L2 GMM: 0.873521 | L2 to x*: 5.290851

 92%|█████████▏| 23/25 [10:58<00:57, 28.85s/it]

[23] seed=64 | L2 GMM: 0.196917 | L2 to x*: 2.782871

 96%|█████████▌| 24/25 [11:26<00:28, 28.74s/it]

[24] seed=65 | L2 GMM: 0.170569 | L2 to x*: 3.487508

100%|██████████| 25/25 [11:55<00:00, 28.62s/it]

[25] seed=66 | L2 GMM: 0.504536 | L2 to x*: 13.062667

## Results

In [ ]:
rows = [
    experiment_utils.summary_row("MLGD",    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.summary_row("MLGD-F", l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df = pd.DataFrame(rows).set_index("Method")
display(df)

rows_top10 = [
    experiment_utils.top10_stats("MLGD",    final_loss_LGD,    l2_gmm_LGD_list,    l2_x_LGD_list,    lgd_times),
    experiment_utils.top10_stats("MLGD-F", final_loss_LGD_CM, l2_gmm_LGD_CM_list, l2_x_LGD_CM_list, lgd_cm_times),
]
df_top10 = pd.DataFrame(rows_top10).set_index("Method")
display(df_top10)

,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s)
Method,,,,,,
LGD,0.5981,0.2601,14.2322,11.4190,421.62,2.17
LGD-CM,0.4185,0.2785,11.9210,11.4937,28.61,0.25

,Loss mean,Loss std,L2 GMM mean,L2 GMM std,L2 to x* mean,L2 to x* std,Time mean (s),Time std (s),Top-k selected
Method,,,,,,,,,
LGD,0.4923,0.2728,0.4385,0.2516,14.4271,11.8886,422.81,2.43,10
LGD-CM,0.2207,0.1351,0.2701,0.1800,6.0726,4.0360,28.62,0.25,10

In [ ]:
def to_python(val):
    if isinstance(val, torch.Tensor):
        return val.detach().cpu().tolist()
    if isinstance(val, np.ndarray):
        return val.tolist()
    if hasattr(val, "item"):
        return val.item()
    return val

results = {
    "experiment":  EXPERIMENT_NAME,
    "seed":        GLOBAL_SEED,
    "environment": env_info,
    "LGD": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_list],
        "final_loss": [to_python(l) for l in final_loss_LGD],
        "l2_gmm":     l2_gmm_LGD_list,
        "l2_x":       l2_x_LGD_list,
        "times":      lgd_times,
    },
    "LGD-CM": {
        "x_pred":     [to_python(x) for x in best_x_t_LGD_CM_list],
        "final_loss": [to_python(l) for l in final_loss_LGD_CM],
        "l2_gmm":     l2_gmm_LGD_CM_list,
        "l2_x":       l2_x_LGD_CM_list,
        "times":      lgd_cm_times,
    },
    "meta": {
        "n_attemp_optim":            N_ATTEMP_OPTIM,
        "nsamples_in_optim_for_mmd": NSAMPLES_IN_OPTIM_FOR_MMD,
        "x_star":                    to_python(x_star),
    },
}

path = os.path.join(RESULTS_DIR, f"{EXPERIMENT_NAME}_results_seed{GLOBAL_SEED}.json")
with open(path, "w") as f:
    json.dump(results, f, indent=2)
print(f"Results saved to {path}")

Results saved to /content/conditional-matching-paper/simulations/results/10D_cond_1D/10D_cond_1D_results_seed42.json